/**
 * hackademy.io's pages: the tutorials, written as the wiki of the people who run the site.
 *
 * Each page is plain HTML within what `lynx` renders — headings, paragraphs, lists, `<pre>`
 * and links — served as files from the box's document root, so a rooted hackademy can be
 * defaced like any other site. Every command a page shows sits in a `<pre>` behind a
 * prompt (`$ ` as the player, `# ` as root), and every example runs on the reader's own
 * box: the pages teach the tools and leave putting them together to the reader.
 */

/** A page. `description` is what a search engine says of it in a listing: only the front
 *  page is listed, so only the front page gives one. */
const page = (title: string, body: readonly string[], description?: string): string =>
  [
    '<html>',
    description === undefined
      ? `<head><title>${title}</title></head>`
      : `<head><title>${title}</title><meta name="description" content="${description}"></head>`,
    '<body>',
    ...body,
    '</body>',
    '</html>',
    '',
  ].join('\n');

const BACK = '<p><a href="/">Back to the front page</a></p>';

/** The way on to the chapter after this one: the chapters are written to be read in order. */
const next = (href: string, title: string): string =>
  `<p>Next: <a href="${href}">${title}</a></p>`;

const FRONT_PAGE = page(
  'hackademy.io',
  [
    '<h1>hackademy.io</h1>',
    '<p>Everybody who ever got anywhere started where you are now: at a prompt, on a box,',
    'knowing nothing. These pages are what we wish somebody had handed us.</p>',
    '<p>Read them in order. Every example runs on your own box, so try each one as you go.',
    'What you do with it afterwards is your business.</p>',
    '<h2>Chapters</h2>',
    '<ol>',
    '<li><a href="/getting-around.html">Getting around</a>: files, users, and the tools your box',
    'came with</li>',
    '<li><a href="/wifi.html">Wifi</a>: how you got on a network in the first place</li>',
    '<li><a href="/your-network.html">Your box and its network</a>: your address, the gateway, and',
    'what the outside sees of you</li>',
    '<li><a href="/looking-around.html">Looking around</a>: asking what is out there, and what it',
    'is running</li>',
    '<li><a href="/getting-in.html">Getting in</a>: the doors onto a box, and the credentials they',
    'want</li>',
    '<li><a href="/services.html">Services, versions and CVEs</a>: what your box runs, and why its',
    'version matters</li>',
    '<li><a href="/the-web.html">The web</a>: reading sites, running one, and finding what is out',
    'there</li>',
    '</ol>',
  ],
  'Tutorials for newcomers: how boxes, networks and the tools that touch them work, a chapter at a time, tried on your own box.',
);

const GETTING_AROUND = page('Getting around', [
  '<h1>Getting around</h1>',
  '<p>You have a shell. It reads what you type, runs it, and prints what comes back.',
  'Everything else on this site is built on the handful of commands below.</p>',

  '<h2>Where you are</h2>',
  '<p>Your box keeps its files in one tree that starts at <code>/</code>. Your own corner',
  'of it is your home directory, <code>/home/</code> and your name, and <code>~</code> is',
  'shorthand for it.</p>',
  '<pre>',
  '$ whoami',
  '$ pwd',
  '$ ls',
  '$ ls -a',
  '$ ls -l',
  '$ cd /var/log',
  '$ cd ~',
  '$ cat README',
  '</pre>',
  '<p><code>ls -a</code> also shows hidden files, the ones whose names start with a dot.',
  '<code>ls -l</code> shows who owns each file and who may read or change it.</p>',

  '<h2>Who you are</h2>',
  '<p>Every box has users. You are one. <code>root</code> is another, and root can read',
  'and change everything. Most boxes keep a <code>guest</code> account too, for visitors.',
  '<code>/etc/passwd</code> lists them all.</p>',
  '<pre>',
  '$ cat /etc/passwd',
  '$ su root',
  '# whoami',
  '# exit',
  '</pre>',
  '<p><code>su</code> asks for root&#39;s password: on your own box, the one you chose when',
  'you set it up. The prompt turns from <code>$</code> to <code>#</code> while you are',
  'root, and <code>exit</code> hands root back.</p>',

  '<h2>Making and changing files</h2>',
  '<pre>',
  '$ mkdir notes',
  '$ cd notes',
  '$ touch todo.txt',
  '$ nano todo.txt',
  '$ echo "buy more coffee" &gt; list.txt',
  '$ cat list.txt',
  '$ rm list.txt',
  '</pre>',
  '<p><code>nano</code> opens a file in an editor: Ctrl-O writes it out and Ctrl-X leaves.',
  '<code>&gt;</code> sends what a command prints into a file instead of to your screen,',
  'replacing whatever the file held.</p>',

  '<h2>Getting more tools</h2>',
  '<p>Your box comes with the basics. Everything else comes from the package repository,',
  'over whatever network you are on, and installing is root&#39;s job. That is how you got',
  'the browser you are reading this in.</p>',
  '<pre>',
  '# apt list',
  '# apt install nmap',
  '# apt list --installed',
  '</pre>',

  '<h2>When you are lost</h2>',
  '<pre>',
  '$ help',
  '$ man ls',
  '$ man apt',
  '</pre>',
  '<p><code>help</code> lists every command this box knows. <code>man</code> shows the',
  'manual for one of them: what it takes, and examples.</p>',

  '<h2>Practice</h2>',
  '<ol>',
  '<li>Find out who you are, then where you are, then what is in your home directory.</li>',
  '<li>Read <code>/etc/passwd</code> and count the users on your box.</li>',
  '<li>Become root, check it with <code>whoami</code>, and hand root back.</li>',
  '<li>Make a directory called <code>notes</code>, write a file in it with',
  '<code>nano</code>, and read it back with <code>cat</code>.</li>',
  '<li>Install a tool from the repository, then read its manual.</li>',
  '</ol>',
  next('/wifi.html', 'Wifi'),
  BACK,
]);

const WIFI = page('Wifi', [
  '<h1>Wifi</h1>',
  '<p>A box with no network reaches nothing: no repository, no sites, no other machines.',
  'The first thing anyone does is get on a network, and most of the time that means a wifi',
  'network whose key you do not have yet. The tools below are how you find one and get on it.</p>',

  '<h2>Listen first</h2>',
  '<p>A wifi card normally talks to one network at a time. Monitor mode turns it into an ear',
  'instead: it stops associating and just listens to everything in the air. You need it on',
  'before you can scan, and off again before you can connect.</p>',
  '<pre>',
  '$ airmon-ng start wlan0',
  '$ airmon-ng stop wlan0',
  '</pre>',

  '<h2>What is in range</h2>',
  '<p>With the card listening, <code>airodump-ng</code> shows every access point it can hear,',
  'one per line: its BSSID (the hardware address of the access point), how strong the signal',
  'is, the channel, how it is encrypted, and its ESSID (the name it advertises). A stronger',
  'signal is a closer network, and a closer network is a faster crack.</p>',
  '<pre>',
  '$ airmon-ng start wlan0',
  '$ airodump-ng',
  '</pre>',

  '<h2>The key</h2>',
  '<p>Give <code>aircrack-ng</code> a BSSID from that list and it tries a wordlist against the',
  'network until one word is the key, or it runs out. Some networks it cannot do anything with:',
  'WPA3 does not give up a handshake this way, a signal too weak never captures one, and a',
  'network hiding its name has nothing for the attack to work from. The rest come down to',
  'whether the key is in the list.</p>',
  '<pre>',
  '$ aircrack-ng BSSID',
  '</pre>',

  '<h2>Get on</h2>',
  '<p>Once you have the name and the key, turn monitor mode off and connect with',
  '<code>nmcli</code>. From then on your box is on that network: it has an address, and the',
  'rest of this site is a <code>lynx</code> away. <code>nmcli status</code> tells you where you',
  'stand.</p>',
  '<pre>',
  '$ airmon-ng stop wlan0',
  '$ nmcli connect ESSID PASSWORD',
  '$ nmcli status',
  '$ nmcli disconnect',
  '</pre>',

  '<h2>Practice</h2>',
  '<ol>',
  '<li>Put <code>wlan0</code> into monitor mode and scan for networks with',
  '<code>airodump-ng</code>.</li>',
  '<li>Pick the one with the strongest signal and read its BSSID and ESSID off the table.</li>',
  '<li>Try to recover its key with <code>aircrack-ng</code>. If it will not crack, read the',
  'reason and try another.</li>',
  '<li>Turn monitor mode off, connect with <code>nmcli connect</code>, and check',
  '<code>nmcli status</code>.</li>',
  '<li>Read <code>man aircrack-ng</code> for what each argument means.</li>',
  '</ol>',
  next('/your-network.html', 'Your box and its network'),
  BACK,
]);

const YOUR_NETWORK = page('Your box and its network', [
  '<h1>Your box and its network</h1>',
  '<p>You are on a network now. This chapter is about where exactly you are on it, how traffic',
  'leaves it, and how the outside world sees you.</p>',

  '<h2>Your address</h2>',
  '<p><code>ifconfig</code> shows your interfaces. The one that matters is <code>wlan0</code>:',
  'its <code>inet</code> line is the address your network leased you, and its <code>gateway</code>',
  'line is the box all your traffic goes out through — the <code>.1</code> of your network.',
  'Everyone else on the network has an address in the same range.</p>',
  '<pre>',
  '$ ifconfig',
  '$ ifconfig wlan0',
  '$ nmcli status',
  '</pre>',

  '<h2>The gateway, and your one address to the world</h2>',
  '<p>Your network address is private: it means nothing outside your own network. To the rest',
  'of the world your whole network is a single public address — the gateway&#39;s. Every box on',
  'your network shares it, and every site you visit sees it and writes it down. You do not pick',
  'it and no command on your box prints it; you learn it the way everyone else does, by reading',
  'it in a log somewhere.</p>',
  '<p>Because the outside only ever reaches that one address, the gateway decides what, if',
  'anything, behind it a stranger can touch. By default: nothing. The gateway opens a way in',
  'only when its own rules file says to — a <code>forward</code> line sending one of its public',
  'ports to a port on one box inside:</p>',
  '<pre>',
  'forward 2222 to ADDRESS:22',
  '</pre>',
  '<p>That is a line in <code>/etc/iptables/rules.v4</code> on the gateway, not a command — the',
  'gateway is its own machine, with its own root account, and editing that file means getting in',
  'there first.</p>',

  '<h2>Closing a port on your own box</h2>',
  '<p>The same file, on your box, does the opposite job. A service you run listens to the whole',
  'network by default. A <code>deny</code> line shuts one port to the network while the service',
  'keeps running for you on <code>localhost</code> — a quieter door than stopping it outright.',
  'A fresh box has no such file, so you make the directory and write one:</p>',
  '<pre>',
  '$ su root',
  '# mkdir -p /etc/iptables',
  '# nano /etc/iptables/rules.v4',
  '# cat /etc/iptables/rules.v4',
  '</pre>',
  '<p>One rule per line, <code>deny PORT</code>. Nothing is denied until you write a line, and a',
  'port you deny still answers you on <code>localhost</code> — the filter is about the network,',
  'not about you.</p>',

  '<h2>Practice</h2>',
  '<ol>',
  '<li>Read your leased address and your gateway off <code>ifconfig wlan0</code>.</li>',
  '<li>Notice that nothing on your box prints your public address — only the networks you visit',
  'know it.</li>',
  '<li>As root, make <code>/etc/iptables</code> and write a <code>rules.v4</code> with a single',
  '<code>deny</code> line for a port you are not using.</li>',
  '<li>Read it back with <code>cat</code>.</li>',
  '<li>Read <code>man ifconfig</code> for the other interfaces it can show you.</li>',
  '</ol>',
  next('/looking-around.html', 'Looking around'),
  BACK,
]);

const LOOKING_AROUND = page('Looking around', [
  '<h1>Looking around</h1>',
  '<p>Before you can do anything with another box you have to find it and learn a little about',
  'it. These tools ask the questions, from the gentlest to the most telling. Point them at your',
  'own box first — every one of them works on <code>ADDRESS</code>, the address you read off',
  '<code>ifconfig</code>.</p>',

  '<h2>Is anything there</h2>',
  '<p><code>ping</code> asks the one question underneath all the others: does an address answer',
  'at all. It tells you a box is reachable and nothing more — a box that answers may be running',
  'nothing worth reaching. It is cheap, so it is where you start.</p>',
  '<pre>',
  '$ ping ADDRESS',
  '$ ping -c 1 ADDRESS',
  '</pre>',

  '<h2>What is it running</h2>',
  '<p><code>nmap</code> scans an address for open ports and names the service behind each one.',
  'With <code>-sV</code> it goes further: it reads the version of the software on each port, and',
  'if a vulnerability has been published against that version, it prints its CVE number and how',
  'severe it is. Run it on your own address and you see your box the way the network sees it.</p>',
  '<pre>',
  '$ nmap ADDRESS',
  '$ nmap -sV ADDRESS',
  '</pre>',
  '<p>A whole network can be swept at once rather than one address at a time;',
  '<code>man nmap</code> shows how to give it a range.</p>',

  '<h2>Names and addresses</h2>',
  '<p>People and machines use names; the network routes on addresses. <code>dig</code> and',
  '<code>nslookup</code> turn one into the other. <code>nslookup</code> gives you the short',
  'answer, <code>dig</code> the full record the name server hands over. Both answer for the',
  'network you are on and for sites published to the whole world, such as this one. A name',
  'nobody has reports <code>NXDOMAIN</code>.</p>',
  '<pre>',
  '$ nslookup hackademy.io',
  '$ dig hackademy.io',
  '</pre>',

  '<h2>Who holds it</h2>',
  '<p><code>whois</code> asks the registry who is behind a public address or a domain: the',
  'network&#39;s name, the organisation that holds it, the site it answers to, and where it',
  'stands. It is how you turn an address you saw in a log into something you know something',
  'about.</p>',
  '<pre>',
  '$ whois hackademy.io',
  '</pre>',

  '<h2>Practice</h2>',
  '<ol>',
  '<li>Read your own address off <code>ifconfig</code>, then <code>ping</code> it.</li>',
  '<li>Scan it with <code>nmap</code>, then again with <code>-sV</code>, and read what your box',
  'is running.</li>',
  '<li>Look up <code>hackademy.io</code> with both <code>nslookup</code> and <code>dig</code>,',
  'and compare what each tells you.</li>',
  '<li>Run <code>whois hackademy.io</code> and see who stands behind this site.</li>',
  '<li>Read <code>man nmap</code> for how to scan a range of addresses at once.</li>',
  '</ol>',
  next('/getting-in.html', 'Getting in'),
  BACK,
]);

const GETTING_IN = page('Getting in', [
  '<h1>Getting in</h1>',
  '<p>Finding a box tells you it is there; getting in is opening a session on it. Every way in',
  'comes down to a door that is listening and a credential it accepts. You already hold every',
  'credential to one box — your own — so that is where you learn what each tool does.</p>',

  '<h2>The doors</h2>',
  '<p><code>ssh</code> is the one you will use most: give it an account and a host and it opens a',
  'shell on that box, as that account. <code>ftp</code> opens a file session instead of a shell,',
  'for a box running an FTP server. <code>scp</code> copies a file over the same channel ssh uses,',
  'from your box to another or back. Pointed at <code>localhost</code> they all reach the box you',
  'are standing on.</p>',
  '<pre>',
  '$ ssh USERNAME@localhost',
  '$ ssh root@localhost',
  '$ ftp localhost',
  '$ scp notes.txt USERNAME@localhost:/tmp/notes.txt',
  '</pre>',
  '<p>On another box the host is an address instead of <code>localhost</code>, and the account and',
  'its password are the credential you had to come by first. A door that is not listening answers',
  'with a refusal, not a prompt.</p>',

  '<h2>Talking to a port</h2>',
  '<p>Under every door is a port. <code>nc</code> speaks to one directly: connect to a port to see',
  'what answers, or, as root, hold one open yourself and wait for something to connect. It is the',
  'bare wire the other tools dress up.</p>',
  '<pre>',
  '$ nc localhost 22',
  '# nc -l 4444',
  '$ nc localhost 4444',
  '</pre>',

  '<h2>Turning a lock into a key</h2>',
  '<p>A door you have no credential for is a lock, and a lock in this world is a password you have',
  'not guessed yet. Both tools that guess work the same way: a wordlist, tried one word at a time,',
  'and a password that is not in the list is never found however weak it looks. The list lives at',
  '<code>/usr/share/wordlists/passwords.txt</code> and arrives with <code>apt install hydra</code>;',
  'you grow it by hand as you go.</p>',
  '<p><code>john</code> works on hashes you already hold — a <code>passwd</code> file you can read.',
  'It touches no network and writes to no log, so it is the quiet one. Point it at your own',
  'box&#39;s accounts to watch it work:</p>',
  '<pre>',
  '# apt install hydra',
  '# john /etc/passwd',
  '</pre>',
  '<p><code>hydra</code> is the loud one: it tries the same wordlist against a live service — an',
  'account over <code>ssh</code>, say — by knocking on it for real, so every word it tries is a',
  'line in that box&#39;s own logs. <code>man hydra</code> has its shape; there is nothing on your',
  'own box to point it at that <code>john</code> cannot answer more quietly.</p>',
  '<pre>',
  '$ man hydra',
  '</pre>',

  '<h2>Practice</h2>',
  '<ol>',
  '<li>Open a shell on your own box with <code>ssh USERNAME@localhost</code>, then leave it with',
  '<code>exit</code>.</li>',
  '<li>As root, hold a port open with <code>nc -l 4444</code>; from another shell reach it with',
  '<code>nc localhost 4444</code> and type a line.</li>',
  '<li>Install the wordlist with <code>apt install hydra</code>, then crack your own box&#39;s',
  'accounts with <code>john /etc/passwd</code>.</li>',
  '<li>Copy a file to another spot on your box with <code>scp</code>.</li>',
  '<li>Read <code>man hydra</code> and <code>man ssh</code> for what each argument means.</li>',
  '</ol>',
  next('/services.html', 'Services, versions and CVEs'),
  BACK,
]);

const SERVICES = page('Services, versions and CVEs', [
  '<h1>Services, versions and CVEs</h1>',
  '<p>A box is not just files and a shell. It runs services — programs that sit listening on a',
  'port so other boxes can talk to them. An open port in a scan is a service; this chapter is',
  'what those services are, and why their version is the most interesting thing about them.</p>',

  '<h2>What is running</h2>',
  '<p><code>ps</code> lists the processes alive on your box right now. <code>systemctl</code> is',
  'how you see and steer the ones that are services: which are up, and starting or stopping them.',
  'Starting a service opens its port to the network; stopping it closes it.</p>',
  '<pre>',
  '$ ps',
  '$ ps aux',
  '$ systemctl status',
  '# systemctl start SERVICE',
  '# systemctl stop SERVICE',
  '</pre>',

  '<h2>Versions, and what is wrong with them</h2>',
  '<p>Every service is a particular version of a particular piece of software, and software has',
  'bugs. Some bugs are holes: a way to make the service do something it should not, written up',
  'for the world to read as a CVE — an identifier, the version range it applies to, and how bad',
  'it is. <code>nmap -sV</code> reads those version numbers off a box from the outside; from the',
  'inside, apt knows exactly what you run and which of it has a published hole.</p>',
  '<pre>',
  '# apt update',
  '# apt list --upgradable',
  '# apt upgrade',
  '</pre>',
  '<p><code>apt list --upgradable</code> names the packages on your box a fix has shipped for —',
  'which is the same list as the ones still carrying the hole until you act. <code>apt upgrade</code>',
  'closes them. A box nobody upgrades keeps its holes for as long as it stays up.</p>',

  '<h2>The other side of a CVE</h2>',
  '<p>A published hole is a door for whoever reaches the box first. <code>msfconsole</code> is the',
  'workbench for that: ready-made attacks indexed by CVE, each matched to a service and a version.',
  'It only matters while a hole is open — a version behind the fix, and only until someone runs',
  '<code>apt upgrade</code>. <code>man msfconsole</code> describes it; what it is for is a box that',
  'is not yours, so there is nothing here to practise it on.</p>',
  '<pre>',
  '$ man msfconsole',
  '</pre>',

  '<h2>Practice</h2>',
  '<ol>',
  '<li>List what is running with <code>ps</code>, then your services with',
  '<code>systemctl status</code>.</li>',
  '<li>Start a service, scan your own address to watch the port open, then stop it again.</li>',
  '<li>Run <code>apt list --upgradable</code> and read which of your software carries a published',
  'hole.</li>',
  '<li>Close them with <code>apt upgrade</code>, then list again to see the difference.</li>',
  '<li>Read <code>man msfconsole</code> to see how a CVE becomes a way in.</li>',
  '</ol>',
  next('/the-web.html', 'The web'),
  BACK,
]);

const THE_WEB = page('The web', [
  '<h1>The web</h1>',
  '<p>A website is just a service — a web server on port 80, serving files to anyone who asks.',
  'You are reading one now. This chapter is how you read them, how you run one, and how you find',
  'what a site did not mean to show you.</p>',

  '<h2>Reading a site</h2>',
  '<p><code>curl</code> fetches one page and prints it raw: the HTML, exactly as the server sent',
  'it. <code>lynx</code> is the browser you came in on — it renders that HTML and follows links.',
  'Reach for <code>curl</code> when you want the bytes, <code>lynx</code> when you want to read.</p>',
  '<pre>',
  '$ curl http://hackademy.io/',
  '$ curl http://hackademy.io/robots.txt',
  '$ lynx http://hackademy.io',
  '</pre>',
  '<p>Many sites keep a <code>robots.txt</code> — a plain list of the paths they would rather stay',
  'out of listings. It is a request, not a lock, and it doubles as a map of what the owner thought',
  'was worth keeping quiet.</p>',

  '<h2>Running your own</h2>',
  '<p>The two common web servers are <code>nginx</code> and <code>apache2</code>. Install one and',
  'start it and your own box serves whatever is in its document root to the network — you are a',
  'site now, with everything that means.</p>',
  '<pre>',
  '# apt install nginx',
  '# systemctl start SERVICE',
  '$ curl http://localhost/',
  '</pre>',

  '<h2>What a site did not link</h2>',
  '<p>A page only tells you about the paths it links to. <code>gobuster</code> asks about the ones',
  'it does not: it walks a list of likely names against a server and reports each that answers, so',
  'a directory nobody linked turns up anyway. Every name it tries is a line in that server&#39;s',
  'access log, so it is a loud way to look. Point it at your own server to see what it exposes.</p>',
  '<pre>',
  '# apt install gobuster',
  '$ gobuster http://localhost',
  '</pre>',

  '<h2>Finding sites at all</h2>',
  '<p>None of this helps until you know a site is there. findit is a search site: it indexes the',
  'web the world can reach and answers for a name or a word, the way you found your way here.',
  'Point <code>lynx</code> at findit, search for something, and follow what comes back.</p>',

  '<h2>Practice</h2>',
  '<ol>',
  '<li>Fetch this page&#39;s raw HTML with <code>curl</code>, then read it in <code>lynx</code>,',
  'and notice the difference.</li>',
  '<li>Read this site&#39;s <code>robots.txt</code>, if it has one.</li>',
  '<li>Install a web server, start it, and fetch <code>http://localhost/</code> from your own',
  'box.</li>',
  '<li>Sweep your own server with <code>gobuster http://localhost</code> and read what answers.</li>',
  '<li>Open findit in <code>lynx</code>, search for a word, and read <code>man gobuster</code> for',
  'how to grow its list.</li>',
  '</ol>',
  BACK,
]);

/** Every page the site serves, by its file name under the document root. */
export const HACKADEMY_PAGES: Readonly<Record<string, string>> = {
  'index.html': FRONT_PAGE,
  'getting-around.html': GETTING_AROUND,
  'wifi.html': WIFI,
  'your-network.html': YOUR_NETWORK,
  'looking-around.html': LOOKING_AROUND,
  'getting-in.html': GETTING_IN,
  'services.html': SERVICES,
  'the-web.html': THE_WEB,
};
