// Credential leak templates — careless user credentials found in guest-readable locations.
// {{username}} and {{password}} are filled with an actual user-type account on the machine.
// binary: true means the file is wrapped in binary noise (requires `strings` to read cleanly).
export type CredentialLeakTemplate = {
  readonly path: string;
  readonly content: string;
  readonly binary?: boolean;
};

export const credentialLeakTemplates: readonly CredentialLeakTemplate[] = [
  // /etc/ config files
  {
    path: '/etc/maintenance.conf',
    content: [
      '# Automated maintenance configuration',
      '# Last updated: 2024-03-15',
      '[remote_backup]',
      'host = 10.0.0.1',
      'user = {{username}}',
      'pass = {{password}}',
      'schedule = daily 02:00',
      'compress = gzip',
    ].join('\n'),
  },
  {
    path: '/etc/crontab',
    content: [
      'SHELL=/bin/bash',
      'PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin',
      '',
      '# m h dom mon dow user command',
      '17 * * * * root cd / && run-parts --report /etc/cron.hourly',
      '25 6 * * * root test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )',
      `0 2 * * * {{username}} /opt/backup.sh --user={{username}} --pass={{password}}`,
      '47 6 * * 7 root test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )',
    ].join('\n'),
  },
  // /srv/www/ and /var/www/ web configs
  {
    path: '/srv/www/.env',
    content: [
      'APP_ENV=production',
      'APP_DEBUG=false',
      'APP_KEY=base64:Rg2Kf8Q7vYz3mXpNsL0wJh6dBtCeAuWi9oElGnHjDs=',
      '',
      'DB_CONNECTION=mysql',
      'DB_HOST=127.0.0.1',
      'DB_PORT=3306',
      'DB_DATABASE=app_prod',
      'DB_USERNAME={{username}}',
      'DB_PASSWORD={{password}}',
      '',
      'CACHE_DRIVER=redis',
      'SESSION_DRIVER=file',
    ].join('\n'),
  },
  {
    path: '/var/www/config.php.bak',
    content: [
      '<?php',
      '// Database configuration — backed up before migration',
      '$db_host = "localhost";',
      '$db_name = "webapp";',
      '$db_user = "{{username}}";',
      '$db_pass = "{{password}}";',
      '',
      '$db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);',
      '?>',
    ].join('\n'),
  },
  // /tmp/ forgotten scripts and logs
  {
    path: '/tmp/.backup.sh',
    content: [
      '#!/bin/bash',
      '# Quick backup script — delete after use',
      'TIMESTAMP=$(date +%Y%m%d_%H%M%S)',
      `REMOTE_USER="{{username}}"`,
      `REMOTE_PASS="{{password}}"`,
      '',
      'mysqldump -u $REMOTE_USER -p$REMOTE_PASS --all-databases > /tmp/dump_$TIMESTAMP.sql',
      'echo "Backup complete: /tmp/dump_$TIMESTAMP.sql"',
    ].join('\n'),
  },
  {
    path: '/tmp/deploy.log',
    content: [
      '[2024-03-12 14:23:01] Starting deployment v4.2.1',
      '[2024-03-12 14:23:02] Connecting to database...',
      `[2024-03-12 14:23:02] Using credentials: {{username}} / {{password}}`,
      '[2024-03-12 14:23:03] Running migrations... OK',
      '[2024-03-12 14:23:05] Restarting services... OK',
      '[2024-03-12 14:23:06] Deployment complete',
      '[2024-03-12 14:23:06] TODO: clean up this log file',
    ].join('\n'),
  },
  // /opt/ and /srv/ application configs
  {
    path: '/opt/app/config.ini',
    content: [
      '[general]',
      'name = app-service',
      'debug = false',
      'log_level = warn',
      '',
      '[database]',
      'host = 127.0.0.1',
      'port = 3306',
      'name = app_data',
      'user = {{username}}',
      'password = {{password}}',
      '',
      '[cache]',
      'driver = redis',
      'host = 127.0.0.1',
      'port = 6379',
    ].join('\n'),
  },
  {
    path: '/opt/app/settings.yml',
    content: [
      'app:',
      '  name: internal-service',
      '  version: 2.1.0',
      '  environment: production',
      '',
      'database:',
      '  driver: postgresql',
      '  host: localhost',
      '  port: 5432',
      '  username: {{username}}',
      '  password: {{password}}',
      '  pool_size: 10',
      '',
      'logging:',
      '  level: info',
      '  output: /var/log/app.log',
    ].join('\n'),
  },
  {
    path: '/srv/app/db.conf',
    content: [
      '# Service database connector',
      '# Auto-generated by setup wizard',
      'DRIVER=mysql',
      'HOST=localhost',
      'PORT=3306',
      'USER={{username}}',
      'PASS={{password}}',
      'MAX_CONNECTIONS=50',
      'TIMEOUT=30',
    ].join('\n'),
  },
  {
    path: '/opt/monitoring/check_service.sh',
    content: [
      '#!/bin/bash',
      '# Health check script — runs every 5 minutes',
      'SERVICE_URL="http://localhost:8080/health"',
      `DB_USER="{{username}}"`,
      `DB_PASS="{{password}}"`,
      '',
      'curl -sf $SERVICE_URL > /dev/null || echo "ALERT: service down"',
      'mysql -u $DB_USER -p$DB_PASS -e "SELECT 1" > /dev/null 2>&1 || echo "ALERT: db down"',
    ].join('\n'),
  },
  // Binary files (require `strings` to read cleanly)
  {
    path: '/usr/local/bin/health_check',
    content: [
      'health_check v2.1.3 — compiled service monitor',
      'config: host=localhost port=8080',
      `credentials: user={{username}} pass={{password}}`,
      'interval: 60s',
      'timeout: 5s',
    ].join('\n'),
    binary: true,
  },
  {
    path: '/opt/lib/libauth.so',
    content: [
      'libauth.so.2.0 — authentication module',
      'default_realm=INTERNAL',
      `service_account={{username}}`,
      `service_secret={{password}}`,
      'token_expiry=3600',
    ].join('\n'),
    binary: true,
  },
  {
    path: '/var/cache/app.db',
    content: [
      'SQLite format 3',
      'CREATE TABLE sessions (id INTEGER PRIMARY KEY, user TEXT, token TEXT);',
      `INSERT INTO credentials VALUES (1, "{{username}}", "{{password}}");`,
      'INSERT INTO sessions VALUES (1, "admin", "tok_a8f3e2b1");',
      'INSERT INTO sessions VALUES (2, "service", "tok_c4d9f0e7");',
    ].join('\n'),
    binary: true,
  },
  // Ansible/automation credential files
  {
    path: '/opt/ansible/host_vars/localhost.yml',
    content: [
      '---',
      '# Ansible host variables',
      'ansible_user: {{username}}',
      'ansible_password: {{password}}',
      'ansible_become: true',
      'ansible_become_method: sudo',
      'http_proxy: ""',
    ].join('\n'),
  },
  {
    path: '/srv/www/wp-config.php.save',
    content: [
      '<?php',
      "define('DB_NAME', 'wordpress');",
      "define('DB_USER', '{{username}}');",
      "define('DB_PASSWORD', '{{password}}');",
      "define('DB_HOST', 'localhost');",
      "define('DB_CHARSET', 'utf8mb4');",
      '',
      "define('AUTH_KEY', 'put-your-unique-phrase-here');",
      '?>',
    ].join('\n'),
  },
  {
    path: '/etc/supervisor/conf.d/app.conf',
    content: [
      '[program:app-worker]',
      'command=/opt/app/worker --db-user={{username}} --db-pass={{password}}',
      'autostart=true',
      'autorestart=true',
      'user=nobody',
      'stdout_logfile=/var/log/worker.log',
      'stderr_logfile=/var/log/worker_err.log',
    ].join('\n'),
  },
  {
    path: '/tmp/.migration_rollback.sql',
    content: [
      '-- Emergency rollback script',
      '-- Created during failed migration on 2024-03-10',
      `-- Credentials: {{username}} / {{password}}`,
      '',
      'BEGIN;',
      'ALTER TABLE users DROP COLUMN mfa_token;',
      'UPDATE schema_version SET version = 41;',
      'COMMIT;',
      '-- TODO: delete this file after rollback',
    ].join('\n'),
  },
  {
    path: '/opt/scripts/sync_remote.sh',
    content: [
      '#!/bin/bash',
      '# Sync files to backup server nightly',
      `RSYNC_USER="{{username}}"`,
      `RSYNC_PASS="{{password}}"`,
      '',
      'export RSYNC_PASSWORD=$RSYNC_PASS',
      'rsync -avz /srv/data/ $RSYNC_USER@10.0.0.50::backup/',
      'echo "$(date): sync completed" >> /var/log/sync.log',
    ].join('\n'),
  },
  {
    path: '/var/www/.git/config',
    content: [
      '[core]',
      '  repositoryformatversion = 0',
      '  filemode = true',
      '[remote "origin"]',
      '  url = https://{{username}}:{{password}}@git.corp.local/webapp.git',
      '  fetch = +refs/heads/*:refs/remotes/origin/*',
      '[branch "main"]',
      '  remote = origin',
      '  merge = refs/heads/main',
    ].join('\n'),
  },
  // Binary files (require `strings` to read cleanly)
  {
    path: '/opt/bin/db_connector',
    content: [
      'db_connector v1.4.0 — database connection pool manager',
      'driver: mysql',
      'host: 127.0.0.1:3306',
      `auth: {{username}}:{{password}}`,
      'pool_size: 25',
      'timeout: 30s',
    ].join('\n'),
    binary: true,
  },
];

// HTTP entry credential templates — placed in /var/www/html/ on the entry machine
// when the entry variant is 'http'. Players discover these via gobuster + curl.
// Body-based: credentials visible in file content via regular curl.
// Header-based (sidecarHeader set): credentials in .headers sidecar, requires curl -i.
export type HttpEntryCredentialTemplate = {
  readonly webPath: string; // Path relative to /var/www/html/, e.g., '.env', 'admin/config.json'
  readonly content: string; // File body (with {{username}}/{{password}} for body-based)
  readonly sidecarHeader?: string; // If set, credential goes in .headers sidecar with this header name
};

export const httpEntryCredentialTemplates: readonly HttpEntryCredentialTemplate[] = [
  // Body-based: credentials in file content
  {
    webPath: '.env',
    content: [
      'APP_ENV=production',
      'APP_DEBUG=false',
      'APP_KEY=base64:Rk9PQkFSQkFaUVVYQ09SR0U=',
      '',
      'DB_CONNECTION=mysql',
      'DB_HOST=127.0.0.1',
      'DB_PORT=3306',
      'DB_DATABASE=webapp',
      '',
      '# SSH tunnel for remote DB access',
      'SSH_USER={{username}}',
      'SSH_PASS={{password}}',
      'SSH_HOST=localhost',
    ].join('\n'),
  },
  {
    webPath: 'admin/config.json',
    content: [
      '{',
      '  "admin": {',
      '    "panel": "/admin/",',
      '    "debug": false',
      '  },',
      '  "ssh": {',
      '    "host": "localhost",',
      '    "user": "{{username}}",',
      '    "password": "{{password}}"',
      '  },',
      '  "backup": {',
      '    "enabled": true,',
      '    "schedule": "daily"',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    webPath: 'api/health',
    content: [
      '{',
      '  "status": "healthy",',
      '  "uptime": "14d 6h 23m",',
      '  "version": "4.2.1",',
      '  "services": {',
      '    "ssh": {',
      '      "user": "{{username}}",',
      '      "pass": "{{password}}",',
      '      "status": "active"',
      '    },',
      '    "http": "running",',
      '    "db": "connected"',
      '  }',
      '}',
    ].join('\n'),
  },
  // Header-based: credentials in .headers sidecar (requires curl -i)
  {
    webPath: 'index.html',
    content: '', // Uses the existing index.html body (no new file created for this path)
    sidecarHeader: 'X-Debug-Token',
  },
  {
    webPath: 'status',
    content: [
      'System Status: OK',
      'Uptime: 14 days, 6 hours',
      'Load: 0.42',
      'Services: ssh(active) http(active) db(active)',
    ].join('\n'),
    sidecarHeader: 'X-Session-Token',
  },
  {
    webPath: 'admin/debug.html',
    content: [
      '<html>',
      '<head><title>Debug Console</title></head>',
      '<body>',
      '<h1>Debug Console</h1>',
      '<p>Debug mode: disabled</p>',
      '<p>Environment: production</p>',
      '<!-- enable debug: ?debug=1 -->',
      '</body>',
      '</html>',
    ].join('\n'),
    sidecarHeader: 'X-Internal-Auth',
  },
  // Body-based: credentials in file content
  {
    webPath: 'backup/credentials.txt',
    content: [
      '# Emergency access credentials',
      '# Created: 2024-03-10 during migration',
      '',
      'SSH_HOST=localhost',
      'SSH_PORT=22',
      'SSH_USER={{username}}',
      'SSH_PASS={{password}}',
      '',
      '# TODO: delete this file after migration completes',
    ].join('\n'),
  },
  {
    webPath: 'api/debug/config',
    content: [
      '{',
      '  "debug": true,',
      '  "env": "staging",',
      '  "build": "4.2.1-rc3",',
      '  "ssh_tunnel": {',
      '    "enabled": true,',
      '    "username": "{{username}}",',
      '    "password": "{{password}}",',
      '    "forward": "localhost:3306"',
      '  }',
      '}',
    ].join('\n'),
  },
  // Header-based: credentials in .headers sidecar (requires curl -i)
  {
    webPath: 'api/v1/health',
    content: [
      '{',
      '  "status": "ok",',
      '  "checks": {',
      '    "database": "connected",',
      '    "cache": "hit_rate_94",',
      '    "queue": "0_pending"',
      '  },',
      '  "version": "3.8.2"',
      '}',
    ].join('\n'),
    sidecarHeader: 'X-Service-Token',
  },
  {
    webPath: 'server-status',
    content: [
      'Server Status for {{hostname}}',
      'Server uptime: 31 days 4 hours 22 minutes',
      'Total accesses: 148203',
      'CPU Usage: u12.3 s4.1',
      '2 requests currently being processed, 8 idle workers',
    ].join('\n'),
    sidecarHeader: 'X-Admin-Credential',
  },
];
