// Credential leak templates — careless user credentials found in guest-readable locations.
// {{username}} and {{password}} are filled with an actual user-type account on the machine.
// binary: true means the file is wrapped in binary noise (requires `strings` to read cleanly).
export type CredentialLeakTemplate = {
  readonly path: string;
  readonly content: string;
  readonly binary?: boolean;
  readonly credentialType?: 'mysql' | 'system';
};

export const credentialLeakTemplates: readonly CredentialLeakTemplate[] = [
  // /etc/ config files
  {
    path: '/etc/maintenance.conf',
    content: [
      '# Automated maintenance configuration',
      '# Last updated: 2024-03-15',
      '[remote_backup]',
      'host = 10.0.0.1',
      'user = {{username}}',
      'pass = {{password}}',
      'schedule = daily 02:00',
      'compress = gzip',
    ].join('\n'),
  },
  {
    path: '/etc/crontab',
    content: [
      'SHELL=/bin/bash',
      'PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin',
      '',
      '# m h dom mon dow user command',
      '17 * * * * root cd / && run-parts --report /etc/cron.hourly',
      '25 6 * * * root test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )',
      `0 2 * * * {{username}} /opt/backup.sh --user={{username}} --pass={{password}}`,
      '47 6 * * 7 root test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )',
    ].join('\n'),
  },
  // /srv/www/ and /var/www/ web configs
  {
    path: '/srv/www/.env',
    credentialType: 'mysql',
    content: [
      'APP_ENV=production',
      'APP_DEBUG=false',
      'APP_KEY=base64:Rg2Kf8Q7vYz3mXpNsL0wJh6dBtCeAuWi9oElGnHjDs=',
      '',
      'DB_CONNECTION=mysql',
      'DB_HOST=127.0.0.1',
      'DB_PORT=3306',
      'DB_DATABASE=app_prod',
      'DB_USERNAME={{username}}',
      'DB_PASSWORD={{password}}',
      '',
      'CACHE_DRIVER=redis',
      'SESSION_DRIVER=file',
    ].join('\n'),
  },
  {
    path: '/var/www/config.php.bak',
    credentialType: 'mysql',
    content: [
      '<?php',
      '// Database configuration — backed up before migration',
      '$db_host = "localhost";',
      '$db_name = "webapp";',
      '$db_user = "{{username}}";',
      '$db_pass = "{{password}}";',
      '',
      '$db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);',
      '?>',
    ].join('\n'),
  },
  // /tmp/ forgotten scripts and logs
  {
    path: '/tmp/.backup.sh',
    credentialType: 'mysql',
    content: [
      '#!/bin/bash',
      '# Quick backup script — delete after use',
      'TIMESTAMP=$(date +%Y%m%d_%H%M%S)',
      `REMOTE_USER="{{username}}"`,
      `REMOTE_PASS="{{password}}"`,
      '',
      'mysqldump -u $REMOTE_USER -p$REMOTE_PASS --all-databases > /tmp/dump_$TIMESTAMP.sql',
      'echo "Backup complete: /tmp/dump_$TIMESTAMP.sql"',
    ].join('\n'),
  },
  {
    path: '/tmp/deploy.log',
    credentialType: 'mysql',
    content: [
      '[2024-03-12 14:23:01] Starting deployment v4.2.1',
      '[2024-03-12 14:23:02] Connecting to database...',
      `[2024-03-12 14:23:02] Using credentials: {{username}} / {{password}}`,
      '[2024-03-12 14:23:03] Running migrations... OK',
      '[2024-03-12 14:23:05] Restarting services... OK',
      '[2024-03-12 14:23:06] Deployment complete',
      '[2024-03-12 14:23:06] TODO: clean up this log file',
    ].join('\n'),
  },
  // /opt/ and /srv/ application configs
  {
    path: '/opt/app/config.ini',
    credentialType: 'mysql',
    content: [
      '[general]',
      'name = app-service',
      'debug = false',
      'log_level = warn',
      '',
      '[database]',
      'host = 127.0.0.1',
      'port = 3306',
      'name = app_data',
      'user = {{username}}',
      'password = {{password}}',
      '',
      '[cache]',
      'driver = redis',
      'host = 127.0.0.1',
      'port = 6379',
    ].join('\n'),
  },
  {
    path: '/opt/app/settings.yml',
    credentialType: 'mysql',
    content: [
      'app:',
      '  name: internal-service',
      '  version: 2.1.0',
      '  environment: production',
      '',
      'database:',
      '  driver: postgresql',
      '  host: localhost',
      '  port: 5432',
      '  username: {{username}}',
      '  password: {{password}}',
      '  pool_size: 10',
      '',
      'logging:',
      '  level: info',
      '  output: /var/log/app.log',
    ].join('\n'),
  },
  {
    path: '/srv/app/db.conf',
    credentialType: 'mysql',
    content: [
      '# Service database connector',
      '# Auto-generated by setup wizard',
      'DRIVER=mysql',
      'HOST=localhost',
      'PORT=3306',
      'USER={{username}}',
      'PASS={{password}}',
      'MAX_CONNECTIONS=50',
      'TIMEOUT=30',
    ].join('\n'),
  },
  {
    path: '/opt/monitoring/check_service.sh',
    credentialType: 'mysql',
    content: [
      '#!/bin/bash',
      '# Health check script — runs every 5 minutes',
      'SERVICE_URL="http://localhost:8080/health"',
      `DB_USER="{{username}}"`,
      `DB_PASS="{{password}}"`,
      '',
      'curl -sf $SERVICE_URL > /dev/null || echo "ALERT: service down"',
      'mysql -u $DB_USER -p$DB_PASS -e "SELECT 1" > /dev/null 2>&1 || echo "ALERT: db down"',
    ].join('\n'),
  },
  // Binary files (require `strings` to read cleanly)
  {
    path: '/usr/local/bin/health_check',
    credentialType: 'mysql',
    content: [
      'health_check v2.1.3 — compiled service monitor',
      'config: host=localhost port=8080',
      `credentials: user={{username}} pass={{password}}`,
      'interval: 60s',
      'timeout: 5s',
    ].join('\n'),
    binary: true,
  },
  {
    path: '/opt/lib/libauth.so',
    content: [
      'libauth.so.2.0 — authentication module',
      'default_realm=INTERNAL',
      `service_account={{username}}`,
      `service_secret={{password}}`,
      'token_expiry=3600',
    ].join('\n'),
    binary: true,
  },
  {
    path: '/var/cache/app.db',
    credentialType: 'mysql',
    content: [
      'SQLite format 3',
      'CREATE TABLE sessions (id INTEGER PRIMARY KEY, user TEXT, token TEXT);',
      `INSERT INTO credentials VALUES (1, "{{username}}", "{{password}}");`,
      'INSERT INTO sessions VALUES (1, "admin", "tok_a8f3e2b1");',
      'INSERT INTO sessions VALUES (2, "service", "tok_c4d9f0e7");',
    ].join('\n'),
    binary: true,
  },
  // Ansible/automation credential files
  {
    path: '/opt/ansible/host_vars/localhost.yml',
    content: [
      '---',
      '# Ansible host variables',
      'ansible_user: {{username}}',
      'ansible_password: {{password}}',
      'ansible_become: true',
      'ansible_become_method: sudo',
      'http_proxy: ""',
    ].join('\n'),
  },
  {
    path: '/srv/www/wp-config.php.save',
    credentialType: 'mysql',
    content: [
      '<?php',
      "define('DB_NAME', 'wordpress');",
      "define('DB_USER', '{{username}}');",
      "define('DB_PASSWORD', '{{password}}');",
      "define('DB_HOST', 'localhost');",
      "define('DB_CHARSET', 'utf8mb4');",
      '',
      "define('AUTH_KEY', 'put-your-unique-phrase-here');",
      '?>',
    ].join('\n'),
  },
  {
    path: '/etc/supervisor/conf.d/app.conf',
    credentialType: 'mysql',
    content: [
      '[program:app-worker]',
      'command=/opt/app/worker --db-user={{username}} --db-pass={{password}}',
      'autostart=true',
      'autorestart=true',
      'user=nobody',
      'stdout_logfile=/var/log/worker.log',
      'stderr_logfile=/var/log/worker_err.log',
    ].join('\n'),
  },
  {
    path: '/tmp/.migration_rollback.sql',
    credentialType: 'mysql',
    content: [
      '-- Emergency rollback script',
      '-- Created during failed migration on 2024-03-10',
      `-- Credentials: {{username}} / {{password}}`,
      '',
      'BEGIN;',
      'ALTER TABLE users DROP COLUMN mfa_token;',
      'UPDATE schema_version SET version = 41;',
      'COMMIT;',
      '-- TODO: delete this file after rollback',
    ].join('\n'),
  },
  {
    path: '/opt/scripts/sync_remote.sh',
    content: [
      '#!/bin/bash',
      '# Sync files to backup server nightly',
      `RSYNC_USER="{{username}}"`,
      `RSYNC_PASS="{{password}}"`,
      '',
      'export RSYNC_PASSWORD=$RSYNC_PASS',
      'rsync -avz /srv/data/ $RSYNC_USER@10.0.0.50::backup/',
      'echo "$(date): sync completed" >> /var/log/sync.log',
    ].join('\n'),
  },
  {
    path: '/var/www/.git/config',
    content: [
      '[core]',
      '  repositoryformatversion = 0',
      '  filemode = true',
      '[remote "origin"]',
      '  url = https://{{username}}:{{password}}@git.corp.local/webapp.git',
      '  fetch = +refs/heads/*:refs/remotes/origin/*',
      '[branch "main"]',
      '  remote = origin',
      '  merge = refs/heads/main',
    ].join('\n'),
  },
  // Binary files (require `strings` to read cleanly)
  {
    path: '/opt/bin/db_connector',
    credentialType: 'mysql',
    content: [
      'db_connector v1.4.0 — database connection pool manager',
      'driver: mysql',
      'host: 127.0.0.1:3306',
      `auth: {{username}}:{{password}}`,
      'pool_size: 25',
      'timeout: 30s',
    ].join('\n'),
    binary: true,
  },
  // Docker / container configs
  {
    path: '/opt/docker/docker-compose.yml',
    credentialType: 'mysql',
    content: [
      'version: "3.8"',
      'services:',
      '  app:',
      '    image: internal/webapp:latest',
      '    environment:',
      '      - DB_HOST=db',
      '      - DB_USER={{username}}',
      '      - DB_PASS={{password}}',
      '    ports:',
      '      - "8080:8080"',
      '    depends_on:',
      '      - db',
      '  db:',
      '    image: mysql:8.0',
      '    volumes:',
      '      - db_data:/var/lib/mysql',
      'volumes:',
      '  db_data:',
    ].join('\n'),
  },
  {
    path: '/opt/docker/.env',
    credentialType: 'mysql',
    content: [
      'COMPOSE_PROJECT_NAME=prod-stack',
      'MYSQL_ROOT_PASSWORD=r00tdb2024',
      'APP_USER={{username}}',
      'APP_PASSWORD={{password}}',
      'REDIS_URL=redis://cache:6379',
      'LOG_LEVEL=warn',
    ].join('\n'),
  },
  // SSH / auth configs
  {
    path: '/opt/deploy/.netrc',
    content: [
      '# auto-generated by deploy script',
      'machine git.corp.local',
      '  login {{username}}',
      '  password {{password}}',
      '',
      'machine registry.corp.local',
      '  login deploy',
      '  password d3pl0y_t0k3n',
    ].join('\n'),
  },
  {
    path: '/opt/app/.pgpass',
    credentialType: 'mysql',
    content: [
      '# hostname:port:database:username:password',
      'localhost:5432:*:{{username}}:{{password}}',
      '10.0.0.5:5432:analytics:readonly:r34d0nly',
    ].join('\n'),
  },
  {
    path: '/etc/mysql/conf.d/client.cnf',
    credentialType: 'mysql',
    content: [
      '[client]',
      'user = {{username}}',
      'password = {{password}}',
      'host = localhost',
      '',
      '[mysqldump]',
      'user = {{username}}',
      'password = {{password}}',
    ].join('\n'),
  },
  // Jenkins / CI configs
  {
    path: '/var/lib/jenkins/credentials.xml',
    content: [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<credentials>',
      '  <entry>',
      '    <id>deploy-ssh</id>',
      '    <description>Production deploy credentials</description>',
      '    <username>{{username}}</username>',
      '    <password>{{password}}</password>',
      '  </entry>',
      '</credentials>',
    ].join('\n'),
  },
  {
    path: '/opt/ci/.gitlab-ci.env',
    content: [
      '# GitLab CI runner environment',
      'CI_DEPLOY_USER={{username}}',
      'CI_DEPLOY_PASSWORD={{password}}',
      'CI_REGISTRY=registry.corp.local:5000',
      'CI_ENVIRONMENT=production',
    ].join('\n'),
  },
  // Tomcat / Java configs
  {
    path: '/opt/tomcat/conf/tomcat-users.xml',
    content: [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<tomcat-users>',
      '  <role rolename="manager-gui"/>',
      '  <role rolename="admin-gui"/>',
      '  <user username="{{username}}" password="{{password}}" roles="manager-gui,admin-gui"/>',
      '</tomcat-users>',
    ].join('\n'),
  },
  // Kubernetes / cloud configs
  {
    path: '/etc/kubernetes/admin.conf',
    content: [
      'apiVersion: v1',
      'kind: Config',
      'clusters:',
      '- cluster:',
      '    server: https://k8s.corp.local:6443',
      '  name: prod-cluster',
      'users:',
      '- name: {{username}}',
      '  user:',
      '    username: {{username}}',
      '    password: {{password}}',
      'contexts:',
      '- context:',
      '    cluster: prod-cluster',
      '    user: {{username}}',
      '  name: prod',
      'current-context: prod',
    ].join('\n'),
  },
  // Log files with leaked credentials
  {
    path: '/opt/app/install.log',
    content: [
      '[2024-01-18 09:14:32] Starting application install',
      '[2024-01-18 09:14:33] Detected OS: Debian 12',
      '[2024-01-18 09:14:34] Creating service account...',
      `[2024-01-18 09:14:34] Set credentials: {{username}} / {{password}}`,
      '[2024-01-18 09:14:35] Installing dependencies... OK',
      '[2024-01-18 09:14:41] Writing systemd unit... OK',
      '[2024-01-18 09:14:42] Installation complete',
    ].join('\n'),
  },
  {
    path: '/opt/app/setup-debug.log',
    credentialType: 'mysql',
    content: [
      'DEBUG config_loader: reading /etc/app/config.yml',
      `DEBUG config_loader: db.username = "{{username}}"`,
      `DEBUG config_loader: db.password = "{{password}}"`,
      'DEBUG config_loader: db.host = "127.0.0.1"',
      'DEBUG pool_manager: opening 10 connections',
      'INFO  app: listening on :8080',
    ].join('\n'),
  },
  // Terraform / IaC
  {
    path: '/opt/terraform/terraform.tfvars',
    credentialType: 'mysql',
    content: [
      '# Production variables — DO NOT commit',
      'region       = "us-east-1"',
      'db_instance  = "db.t3.medium"',
      'db_username  = "{{username}}"',
      'db_password  = "{{password}}"',
      'vpc_cidr     = "10.0.0.0/16"',
    ].join('\n'),
  },
  // Redis / cache configs
  {
    path: '/etc/redis/redis.conf.bak',
    content: [
      '# Redis configuration — backup before upgrade',
      'bind 0.0.0.0',
      'port 6379',
      'requirepass {{password}}',
      '',
      '# Rename dangerous commands',
      'rename-command FLUSHALL ""',
      'rename-command CONFIG ""',
      '',
      '# Added by {{username}} on 2024-02-20',
      'maxmemory 256mb',
      'maxmemory-policy allkeys-lru',
    ].join('\n'),
  },
  // Python / pip configs
  {
    path: '/etc/pip.conf',
    content: [
      '[global]',
      'index-url = https://{{username}}:{{password}}@pypi.corp.local/simple/',
      'trusted-host = pypi.corp.local',
      'timeout = 60',
    ].join('\n'),
  },
  // Nagios / monitoring
  {
    path: '/etc/nagios/resource.cfg',
    content: [
      '# Nagios resource file — macros for plugin auth',
      '# WARNING: contains sensitive credentials',
      '$USER1$=/usr/lib/nagios/plugins',
      '$USER3$={{username}}',
      '$USER4$={{password}}',
    ].join('\n'),
  },
  // Grafana
  {
    path: '/etc/grafana/grafana.ini',
    content: [
      '[server]',
      'http_port = 3000',
      'domain = monitoring.corp.local',
      '',
      '[security]',
      'admin_user = {{username}}',
      'admin_password = {{password}}',
      '',
      '[database]',
      'type = sqlite3',
      'path = /var/lib/grafana/grafana.db',
    ].join('\n'),
  },
  // Backup manifest
  {
    path: '/opt/backups/.credentials',
    content: [
      '# Backup service credentials',
      '# Rotated: 2024-02-01',
      'BACKUP_USER={{username}}',
      'BACKUP_PASS={{password}}',
      'BACKUP_HOST=nas.corp.local',
      'BACKUP_PATH=/mnt/backups/prod',
      'RETENTION_DAYS=30',
    ].join('\n'),
  },
  // Binary files
  {
    path: '/opt/bin/svc_monitor',
    credentialType: 'mysql',
    content: [
      'svc_monitor v3.0.1 — service monitoring daemon',
      'compiled: 2024-01-22 gcc 12.2.0',
      `db_auth={{username}}:{{password}}`,
      'check_interval=30',
      'alert_email=ops@corp.local',
    ].join('\n'),
    binary: true,
  },
  {
    path: '/usr/local/sbin/backup_agent',
    content: [
      'backup_agent v2.3 — incremental backup service',
      `remote_user={{username}}`,
      `remote_pass={{password}}`,
      'target=nas.corp.local:/backups',
      'schedule=0 3 * * *',
    ].join('\n'),
    binary: true,
  },
];

// Cross-machine credential leak templates — found after privilege escalation.
// {{target_ip}}, {{target_username}}, {{target_password}} are filled with a same-layer machine's creds.
// {{owner}} is replaced with the file owner's username (for home directory paths).
// owner controls file permissions: 'root' = only root can read, 'user' = root + user.
export type CrossMachineCredentialLeakTemplate = {
  readonly path: string;
  readonly content: string;
  readonly owner: 'root' | 'user';
  readonly binary?: boolean;
};

export const crossMachineCredentialLeakTemplates: readonly CrossMachineCredentialLeakTemplate[] = [
  // Deploy/automation scripts (root-owned)
  {
    path: '/root/.ssh/config',
    owner: 'root',
    content: [
      'Host internal-server',
      '    HostName {{target_ip}}',
      '    User {{target_username}}',
      '    # Password: {{target_password}}',
      '    StrictHostKeyChecking no',
      '    UserKnownHostsFile /dev/null',
    ].join('\n'),
  },
  {
    path: '/opt/deploy/hosts.ini',
    owner: 'root',
    content: [
      '[webservers]',
      '{{target_ip}} ansible_user={{target_username}} ansible_password={{target_password}}',
      '',
      '[webservers:vars]',
      'ansible_connection=ssh',
      'ansible_become=yes',
    ].join('\n'),
  },
  {
    path: '/opt/ansible/inventory.yml',
    owner: 'root',
    content: [
      'all:',
      '  hosts:',
      '    app-server:',
      '      ansible_host: {{target_ip}}',
      '      ansible_user: {{target_username}}',
      '      ansible_ssh_pass: {{target_password}}',
      '      ansible_become: true',
    ].join('\n'),
  },
  {
    path: '/root/deploy.sh',
    owner: 'root',
    content: [
      '#!/bin/bash',
      '# Deploy script — push latest build to app server',
      'TARGET={{target_ip}}',
      'USER={{target_username}}',
      'PASS={{target_password}}',
      '',
      'sshpass -p "$PASS" scp -o StrictHostKeyChecking=no ./build.tar.gz $USER@$TARGET:/opt/app/',
      'sshpass -p "$PASS" ssh $USER@$TARGET "cd /opt/app && tar xzf build.tar.gz && ./restart.sh"',
    ].join('\n'),
  },
  // Backup scripts (root-owned)
  {
    path: '/etc/cron.d/remote-backup',
    owner: 'root',
    content: [
      'SHELL=/bin/bash',
      '# Nightly backup sync to {{target_ip}}',
      '0 3 * * * root sshpass -p "{{target_password}}" rsync -az /var/backups/ {{target_username}}@{{target_ip}}:/backups/',
    ].join('\n'),
  },
  {
    path: '/opt/backups/sync.sh',
    owner: 'root',
    content: [
      '#!/bin/bash',
      '# Sync local backups to remote storage',
      'REMOTE_HOST={{target_ip}}',
      'REMOTE_USER={{target_username}}',
      'REMOTE_PASS={{target_password}}',
      '',
      'sshpass -p "$REMOTE_PASS" rsync -avz --delete \\',
      '  /var/backups/ $REMOTE_USER@$REMOTE_HOST:/mnt/backups/',
      'echo "[$(date)] Sync complete" >> /var/log/backup-sync.log',
    ].join('\n'),
  },
  {
    path: '/root/.netrc',
    owner: 'root',
    content: [
      'machine {{target_ip}}',
      '  login {{target_username}}',
      '  password {{target_password}}',
    ].join('\n'),
  },
  // App configs referencing remote services (user-owned)
  {
    path: '/home/{{owner}}/projects/.env',
    owner: 'user',
    content: [
      'APP_ENV=development',
      'APP_DEBUG=true',
      '',
      'DB_HOST={{target_ip}}',
      'DB_PORT=3306',
      'DB_USER={{target_username}}',
      'DB_PASS={{target_password}}',
      '',
      'REDIS_HOST={{target_ip}}',
      'REDIS_PORT=6379',
    ].join('\n'),
  },
  {
    path: '/home/{{owner}}/.bash_history',
    owner: 'user',
    content: [
      'ls -la',
      'cd /opt/app',
      'vim config.yml',
      'ssh {{target_username}}@{{target_ip}}',
      'sshpass -p "{{target_password}}" ssh {{target_username}}@{{target_ip}}',
      'cat /var/log/app.log | tail -50',
      'systemctl restart app',
      'exit',
    ].join('\n'),
  },
  // Service configs (root-owned)
  {
    path: '/etc/supervisor/conf.d/tunnel.conf',
    owner: 'root',
    content: [
      '[program:ssh-tunnel]',
      'command=sshpass -p "{{target_password}}" ssh -N -L 3306:localhost:3306 {{target_username}}@{{target_ip}}',
      'autostart=true',
      'autorestart=true',
      'stderr_logfile=/var/log/tunnel.err.log',
      'stdout_logfile=/var/log/tunnel.out.log',
    ].join('\n'),
  },
  {
    path: '/opt/docker/docker-compose.yml',
    owner: 'root',
    content: [
      'version: "3.8"',
      'services:',
      '  app:',
      '    image: app:latest',
      '    environment:',
      '      - DB_HOST={{target_ip}}',
      '      - DB_USER={{target_username}}',
      '      - DB_PASS={{target_password}}',
      '    restart: unless-stopped',
    ].join('\n'),
  },
  // Infrastructure files (root-owned)
  {
    path: '/etc/fstab.bak',
    owner: 'root',
    content: [
      '# /etc/fstab — static filesystem table (backup before NFS migration)',
      'UUID=a1b2c3d4 /              ext4    errors=remount-ro 0 1',
      'UUID=e5f6a7b8 /boot          ext4    defaults          0 2',
      '# NFS mount — credentials in-line for testing',
      '//{{target_ip}}/share /mnt/share cifs username={{target_username}},password={{target_password}},iocharset=utf8 0 0',
    ].join('\n'),
  },
  {
    path: '/opt/scripts/db_check.sh',
    owner: 'root',
    content: [
      '#!/bin/bash',
      '# Check remote database health',
      'DB_HOST={{target_ip}}',
      'DB_USER={{target_username}}',
      'DB_PASS={{target_password}}',
      '',
      'mysql -h $DB_HOST -u $DB_USER -p$DB_PASS -e "SELECT 1" > /dev/null 2>&1',
      'if [ $? -ne 0 ]; then',
      '  echo "CRITICAL: Database at $DB_HOST unreachable" | mail -s "DB Alert" ops@corp.local',
      'fi',
    ].join('\n'),
  },
  // Binary with embedded remote creds
  {
    path: '/usr/local/bin/remote_monitor',
    owner: 'root',
    binary: true,
    content: [
      'remote_monitor v1.4.2 — compiled service checker',
      'target_host={{target_ip}}',
      'auth_user={{target_username}}',
      'auth_pass={{target_password}}',
      'check_interval=120',
      'alert_threshold=3',
    ].join('\n'),
  },
];

// Web credential templates — placed in /var/www/html/ on non-entry machines with HTTP ports.
// {{username}} and {{password}} are filled with a non-root, non-guest user on the machine.
// These are same-machine credentials discoverable via curl/gobuster.
export type WebCredentialTemplate = {
  readonly webPath: string;
  readonly content: string;
  readonly sidecarHeader?: string;
};

export const webCredentialTemplates: readonly WebCredentialTemplate[] = [
  // Body-based: credentials visible in file content
  {
    webPath: '.env.bak',
    content: [
      '# Environment backup — created during migration',
      'APP_ENV=production',
      'APP_DEBUG=false',
      '',
      'SSH_USER={{username}}',
      'SSH_PASS={{password}}',
      'SSH_HOST=localhost',
    ].join('\n'),
  },
  {
    webPath: 'config.php.bak',
    content: [
      '<?php',
      '// Config backup — do not deploy',
      '$ssh_host = "localhost";',
      '$ssh_user = "{{username}}";',
      '$ssh_pass = "{{password}}";',
      '',
      '$db = new PDO("mysql:host=localhost;dbname=app", $ssh_user, $ssh_pass);',
      '?>',
    ].join('\n'),
  },
  {
    webPath: 'api/config',
    content: [
      '{',
      '  "version": "3.1.0",',
      '  "env": "production",',
      '  "ssh": {',
      '    "host": "localhost",',
      '    "user": "{{username}}",',
      '    "password": "{{password}}"',
      '  },',
      '  "debug": false',
      '}',
    ].join('\n'),
  },
  {
    webPath: 'backup/db-dump.sh',
    content: [
      '#!/bin/bash',
      '# Quick DB backup — should not be in webroot',
      'USER="{{username}}"',
      'PASS="{{password}}"',
      'mysqldump -u $USER -p$PASS --all-databases > /tmp/dump.sql',
    ].join('\n'),
  },
  {
    webPath: 'install.php',
    content: [
      '<?php',
      '// Installation wizard — remove after setup!',
      '// Default SSH credentials for setup:',
      '//   user: {{username}}',
      '//   pass: {{password}}',
      '$setup_complete = true;',
      'if (!$setup_complete) { header("Location: /install/step1"); }',
      '?>',
    ].join('\n'),
  },
  // Header-based: credentials in .headers sidecar (requires curl -i)
  {
    webPath: '.well-known/security.txt',
    content: [
      'Contact: mailto:security@corp.local',
      'Preferred-Languages: en',
      'Canonical: /.well-known/security.txt',
      'Policy: /security-policy',
    ].join('\n'),
    sidecarHeader: 'X-Debug-Auth',
  },
  {
    webPath: 'metrics',
    content: [
      '# HELP http_requests_total Total HTTP requests',
      '# TYPE http_requests_total counter',
      'http_requests_total{method="GET",status="200"} 148203',
      'http_requests_total{method="POST",status="200"} 42891',
      'http_requests_total{method="GET",status="404"} 3012',
    ].join('\n'),
    sidecarHeader: 'X-Service-Auth',
  },
  {
    webPath: 'api/v2/status',
    content: [
      '{',
      '  "status": "operational",',
      '  "uptime": "22d 14h",',
      '  "services": {',
      '    "web": "running",',
      '    "db": "connected",',
      '    "cache": "active"',
      '  }',
      '}',
    ].join('\n'),
    sidecarHeader: 'X-Admin-Token',
  },
  {
    webPath: 'debug/info',
    content: [
      '{',
      '  "app": "internal-service",',
      '  "build": "2024-03-15T10:22:00Z",',
      '  "node": "prod-01",',
      '  "memory_mb": 512,',
      '  "pid": 1842',
      '}',
    ].join('\n'),
    sidecarHeader: 'X-Internal-Credential',
  },
  {
    webPath: 'sitemap.xml',
    content: [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
      '  <url><loc>/</loc><priority>1.0</priority></url>',
      '  <url><loc>/status</loc><priority>0.5</priority></url>',
      '</urlset>',
    ].join('\n'),
    sidecarHeader: 'X-Forwarded-Auth',
  },
];

// HTTP entry credential templates — placed in /var/www/html/ on the entry machine
// when the entry variant is 'http'. Players discover these via gobuster + curl.
// Body-based: credentials visible in file content via regular curl.
// Header-based (sidecarHeader set): credentials in .headers sidecar, requires curl -i.
export type HttpEntryCredentialTemplate = {
  readonly webPath: string; // Path relative to /var/www/html/, e.g., '.env', 'admin/config.json'
  readonly content: string; // File body (with {{username}}/{{password}} for body-based)
  readonly sidecarHeader?: string; // If set, credential goes in .headers sidecar with this header name
};

export const httpEntryCredentialTemplates: readonly HttpEntryCredentialTemplate[] = [
  // Body-based: credentials in file content
  {
    webPath: '.env',
    content: [
      'APP_ENV=production',
      'APP_DEBUG=false',
      'APP_KEY=base64:Rk9PQkFSQkFaUVVYQ09SR0U=',
      '',
      'DB_CONNECTION=mysql',
      'DB_HOST=127.0.0.1',
      'DB_PORT=3306',
      'DB_DATABASE=webapp',
      '',
      '# SSH tunnel for remote DB access',
      'SSH_USER={{username}}',
      'SSH_PASS={{password}}',
      'SSH_HOST=localhost',
    ].join('\n'),
  },
  {
    webPath: 'admin/config.json',
    content: [
      '{',
      '  "admin": {',
      '    "panel": "/admin/",',
      '    "debug": false',
      '  },',
      '  "ssh": {',
      '    "host": "localhost",',
      '    "user": "{{username}}",',
      '    "password": "{{password}}"',
      '  },',
      '  "backup": {',
      '    "enabled": true,',
      '    "schedule": "daily"',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    webPath: 'api/health',
    content: [
      '{',
      '  "status": "healthy",',
      '  "uptime": "14d 6h 23m",',
      '  "version": "4.2.1",',
      '  "services": {',
      '    "ssh": {',
      '      "user": "{{username}}",',
      '      "pass": "{{password}}",',
      '      "status": "active"',
      '    },',
      '    "http": "running",',
      '    "db": "connected"',
      '  }',
      '}',
    ].join('\n'),
  },
  // Header-based: credentials in .headers sidecar (requires curl -i)
  {
    webPath: 'index.html',
    content: '', // Uses the existing index.html body (no new file created for this path)
    sidecarHeader: 'X-Debug-Token',
  },
  {
    webPath: 'status',
    content: [
      'System Status: OK',
      'Uptime: 14 days, 6 hours',
      'Load: 0.42',
      'Services: ssh(active) http(active) db(active)',
    ].join('\n'),
    sidecarHeader: 'X-Session-Token',
  },
  {
    webPath: 'admin/debug.html',
    content: [
      '<html>',
      '<head><title>Debug Console</title></head>',
      '<body>',
      '<h1>Debug Console</h1>',
      '<p>Debug mode: disabled</p>',
      '<p>Environment: production</p>',
      '<!-- enable debug: ?debug=1 -->',
      '</body>',
      '</html>',
    ].join('\n'),
    sidecarHeader: 'X-Internal-Auth',
  },
  // Body-based: credentials in file content
  {
    webPath: 'backup/credentials.txt',
    content: [
      '# Emergency access credentials',
      '# Created: 2024-03-10 during migration',
      '',
      'SSH_HOST=localhost',
      'SSH_PORT=22',
      'SSH_USER={{username}}',
      'SSH_PASS={{password}}',
      '',
      '# TODO: delete this file after migration completes',
    ].join('\n'),
  },
  {
    webPath: 'api/debug/config',
    content: [
      '{',
      '  "debug": true,',
      '  "env": "staging",',
      '  "build": "4.2.1-rc3",',
      '  "ssh_tunnel": {',
      '    "enabled": true,',
      '    "username": "{{username}}",',
      '    "password": "{{password}}",',
      '    "forward": "localhost:3306"',
      '  }',
      '}',
    ].join('\n'),
  },
  // Header-based: credentials in .headers sidecar (requires curl -i)
  {
    webPath: 'api/v1/health',
    content: [
      '{',
      '  "status": "ok",',
      '  "checks": {',
      '    "database": "connected",',
      '    "cache": "hit_rate_94",',
      '    "queue": "0_pending"',
      '  },',
      '  "version": "3.8.2"',
      '}',
    ].join('\n'),
    sidecarHeader: 'X-Service-Token',
  },
  {
    webPath: 'server-status',
    content: [
      'Server Status for {{hostname}}',
      'Server uptime: 31 days 4 hours 22 minutes',
      'Total accesses: 148203',
      'CPU Usage: u12.3 s4.1',
      '2 requests currently being processed, 8 idle workers',
    ].join('\n'),
    sidecarHeader: 'X-Admin-Credential',
  },
  // Body-based: credentials in file content
  {
    webPath: 'config/database.yml',
    content: [
      'production:',
      '  adapter: postgresql',
      '  host: localhost',
      '  port: 5432',
      '  database: webapp_prod',
      '  ssh_user: {{username}}',
      '  ssh_password: {{password}}',
      '  pool: 10',
      '  timeout: 5000',
    ].join('\n'),
  },
  {
    webPath: '.git/config',
    content: [
      '[core]',
      '  repositoryformatversion = 0',
      '  filemode = true',
      '[remote "origin"]',
      '  url = https://{{username}}:{{password}}@git.corp.local/webapp.git',
      '  fetch = +refs/heads/*:refs/remotes/origin/*',
      '[branch "main"]',
      '  remote = origin',
      '  merge = refs/heads/main',
    ].join('\n'),
  },
  {
    webPath: 'phpinfo.php',
    content: [
      '<?php',
      '// Temporary debug page — remove before go-live',
      '// SSH access for remote debugging:',
      '//   user: {{username}}',
      '//   pass: {{password}}',
      'phpinfo();',
      '?>',
    ].join('\n'),
  },
  {
    webPath: 'api/internal/whoami',
    content: [
      '{',
      '  "service": "auth-gateway",',
      '  "node": "prod-web-01",',
      '  "tunnel": {',
      '    "type": "ssh",',
      '    "user": "{{username}}",',
      '    "password": "{{password}}"',
      '  },',
      '  "uptime_sec": 1243800',
      '}',
    ].join('\n'),
  },
  {
    webPath: 'wp-config.php.bak',
    content: [
      '<?php',
      "define('DB_NAME', 'wordpress');",
      "define('DB_USER', '{{username}}');",
      "define('DB_PASSWORD', '{{password}}');",
      "define('DB_HOST', 'localhost');",
      '',
      "define('AUTH_KEY', 'z9$kR!mP&4qW^eB');",
      "define('SECURE_AUTH_KEY', 'vN2@xL#8dF+jH5');",
      '?>',
    ].join('\n'),
  },
  // Header-based: credentials in .headers sidecar (requires curl -i)
  {
    webPath: 'robots.txt',
    content: [
      'User-agent: *',
      'Disallow: /admin/',
      'Disallow: /api/internal/',
      'Disallow: /backup/',
    ].join('\n'),
    sidecarHeader: 'X-Forwarded-Credentials',
  },
  {
    webPath: 'health',
    content: [
      '{',
      '  "status": "healthy",',
      '  "checks": {',
      '    "disk": "ok",',
      '    "memory": "ok",',
      '    "database": "ok"',
      '  },',
      '  "version": "2.14.0"',
      '}',
    ].join('\n'),
    sidecarHeader: 'X-Auth-Token',
  },
  {
    webPath: 'admin/login.html',
    content: [
      '<html>',
      '<head><title>Admin Login</title></head>',
      '<body>',
      '<form method="POST" action="/admin/auth">',
      '  <input type="text" name="user" placeholder="Username">',
      '  <input type="password" name="pass" placeholder="Password">',
      '  <button type="submit">Login</button>',
      '</form>',
      '</body>',
      '</html>',
    ].join('\n'),
    sidecarHeader: 'X-Dev-Credentials',
  },
];
