import type { MachineRole } from '../types';
import { secrets } from '../../secrets/__encoded';

export const clientHandles: readonly string[] = [
  'xR0gu3x',
  'gh0st_',
  'cyph3rpunk',
  'n3twr4ith',
  'zer0day_',
  'bl4ckh4t',
  'silkr0ad',
  'darkfl0w',
  'v0id_agent',
  'ph4nt0m',
  'sh4d0w_',
  'n1ghtcr4wl',
  'd34dc0de',
  'r00tk1t_',
  'bytefl00d',
  'cr4sh_0v3r',
  'nullp0int3r',
  'w1r3sh4rk',
  'sp00f3r',
  'h4ckb0x',
];

export const usernamesByRole: Readonly<Record<MachineRole, readonly string[]>> = {
  webserver: [
    'www-data',
    'webadmin',
    'apache',
    'nginx',
    'deploy',
    'devops',
    'httpd',
    'proxy',
    'caddy',
    'webops',
  ],
  database: [
    'dbadmin',
    'postgres',
    'mysql',
    'dba',
    'dataops',
    'dbuser',
    'replication',
    'analytics',
    'etl',
    'sqldev',
  ],
  fileserver: [
    'ftpuser',
    'backup',
    'storage',
    'sysadmin',
    'fileadm',
    'archive',
    'nfs',
    'rsync',
    'datamgr',
    'shareuser',
  ],
  workstation: [
    'jsmith',
    'admin',
    'developer',
    'analyst',
    'operator',
    'mrodriguez',
    'pwilson',
    'sthompson',
    'klee',
    'rjohnson',
  ],
  mailserver: [
    'postmaster',
    'mailadm',
    'dovecot',
    'smtp-svc',
    'mailops',
    'listadm',
    'relay',
    'quarantine',
    'mxops',
    'imapuser',
  ],
  iot: [
    'admin',
    'device',
    'iotuser',
    'sensor',
    'operator',
    'mqtt',
    'telemetry',
    'gateway',
    'controller',
    'monitor',
  ],
  router: [
    'netops',
    'routeadm',
    'admin',
    'fwadmin',
    'operator',
    'bgpuser',
    'snmpadm',
    'vpnuser',
    'natadm',
    'core',
  ],
  switch: [
    'netadmin',
    'switchadm',
    'vlanadm',
    'portadm',
    'l3admin',
    'acluser',
    'switchops',
    'trunkadm',
    'spanadm',
    'uplinkadm',
  ],
};

export const guestPasswords: readonly string[] = JSON.parse(
  secrets.GUEST_PASSWORDS,
) as readonly string[];

export const passwords: readonly string[] = JSON.parse(
  secrets.MISSION_PASSWORDS,
) as readonly string[];

export const hostnamesByRole: Readonly<Record<MachineRole, readonly string[]>> = {
  webserver: [
    'web01',
    'web-prod',
    'www',
    'frontend',
    'apache01',
    'webnode-1',
    'http-srv',
    'proxy01',
    'lb-web',
    'cdn-edge',
  ],
  database: [
    'db-primary',
    'db01',
    'mysql-prod',
    'postgres01',
    'datastore',
    'replica-01',
    'db-analytics',
    'redis-cache',
    'mongo-srv',
    'data-node',
  ],
  fileserver: [
    'files01',
    'nas',
    'backup-srv',
    'storage01',
    'ftp-main',
    'nfs-share',
    'archive01',
    'rsync-srv',
    'samba-dc',
    'backup-nas',
  ],
  workstation: [
    'ws-admin',
    'dev-box',
    'ops-station',
    'analyst-pc',
    'jump-box',
    'workbench',
    'admin-ws',
    'lab-pc',
    'bastion',
    'deploy-box',
  ],
  mailserver: [
    'mail01',
    'mx-primary',
    'smtp-relay',
    'postfix-srv',
    'exchange01',
    'relay-01',
    'imap-srv',
    'mail-gw',
    'mx-backup',
    'mailer01',
  ],
  iot: [
    'cam-01',
    'thermostat',
    'smart-lock',
    'iot-hub',
    'sensor-gw',
    'doorbell',
    'hvac-ctrl',
    'pir-sensor',
    'weather-stn',
    'ip-cam-02',
  ],
  router: [
    'router01',
    'gw-main',
    'border-gw',
    'core-rtr',
    'firewall01',
    'edge-rtr',
    'fw-dmz',
    'switch-core',
    'vpn-gw',
    'net-gateway',
  ],
  switch: [
    'sw-core-01',
    'l3-switch',
    'dist-sw',
    'agg-switch',
    'sw-access',
    'switch-mgmt',
    'sw-dist-01',
    'vlan-sw',
    'trunk-sw',
    'sw-edge',
  ],
};
