import type { MachineRole, ScriptBugType } from '../types';

export type ScriptFixTemplate = {
  readonly path: string;
  readonly bugVariants: Readonly<Record<ScriptBugType, string>>;
  readonly corruptedHintPath: string;
  readonly corruptedHintContent: string;
  readonly expectedChecksum: string;
};

export const scriptFixTemplatesByRole: Readonly<Record<MachineRole, readonly ScriptFixTemplate[]>> =
  {
    fileserver: [
      {
        path: '/srv/scripts/validate_backups.js',
        bugVariants: {
          syntax: [
            'const backups = ["db_full", "db_diff", "logs", "config"]',
            'const critical = backups.filter(b => b.startsWith("db")',
            'if (critical.length === 2) {',
            '  _system(critical.join("-"))',
            '} else {',
            '  echo("ERROR: backup validation failed")',
            '}',
          ].join('\n'),
          logic: [
            'const backups = ["db_full", "db_diff", "logs", "config"]',
            'const critical = backups.filter(b => b.startsWith("db"))',
            'if (critical.length === 3) {',
            '  _system(critical.join("-"))',
            '} else {',
            '  echo("ERROR: backup validation failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const backups = ???',
            'const critical = backups.filter(b => b.startsWith("db"))',
            'if (critical.length === 2) {',
            '  _system(critical.join("-"))',
            '} else {',
            '  echo("ERROR: backup validation failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/srv/scripts/.backup_list',
        corruptedHintContent: 'backup_sources=["db_full", "db_diff", "logs", "config"]',
        expectedChecksum: 'db_full-db_diff',
      },
      {
        path: '/srv/scripts/check_exports.js',
        bugVariants: {
          syntax: [
            'const exports = ["report_q1", "report_q2", "summary", "archive"]',
            'const reports = exports.filter(e => e.startsWith("report"))',
            'if (reports.length === 2) {',
            '  _system(reports.join("-"))',
            '} else {',
            '  echo("ERROR: export check failed")',
            '',
          ].join('\n'),
          logic: [
            'const exports = ["report_q1", "report_q2", "summary", "archive"]',
            'const reports = exports.filter(e => e.startsWith("report"))',
            'if (reports.length === 1) {',
            '  _system(reports.join("-"))',
            '} else {',
            '  echo("ERROR: export check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const exports = ["report_q1", "report_q2", "summary", "archive"]',
            'const reports = exports.filter(e => e.startsWith(???))',
            'if (reports.length === 2) {',
            '  _system(reports.join("-"))',
            '} else {',
            '  echo("ERROR: export check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/srv/scripts/.export_config',
        corruptedHintContent: 'filter_prefix="report"',
        expectedChecksum: 'report_q1-report_q2',
      },
      {
        path: '/srv/scripts/verify_permissions.js',
        bugVariants: {
          syntax: [
            'const shares = [',
            '  { path: "/srv/public", mode: 755 },',
            '  { path: "/srv/private", mode: 700 },',
            '  { path: "/srv/upload", mode: 777 },',
            '  { path: "/srv/archive", mode: 755 }',
            ']',
            'const unsafe = shares.filter(s => s.mode > 755)',
            'if (unsafe.length === 1) {',
            '  _system(unsafe.map(s => s.path).join("-")',
            '} else {',
            '  echo("ERROR: permission check failed")',
            '}',
          ].join('\n'),
          logic: [
            'const shares = [',
            '  { path: "/srv/public", mode: 755 },',
            '  { path: "/srv/private", mode: 700 },',
            '  { path: "/srv/upload", mode: 777 },',
            '  { path: "/srv/archive", mode: 755 }',
            ']',
            'const unsafe = shares.filter(s => s.mode > 777)',
            'if (unsafe.length === 1) {',
            '  _system(unsafe.map(s => s.path).join("-"))',
            '} else {',
            '  echo("ERROR: permission check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const shares = [',
            '  { path: "/srv/public", mode: 755 },',
            '  { path: "/srv/private", mode: 700 },',
            '  { path: "/srv/upload", mode: ??? },',
            '  { path: "/srv/archive", mode: 755 }',
            ']',
            'const unsafe = shares.filter(s => s.mode > 755)',
            'if (unsafe.length === 1) {',
            '  _system(unsafe.map(s => s.path).join("-"))',
            '} else {',
            '  echo("ERROR: permission check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/srv/scripts/.share_perms',
        corruptedHintContent: 'upload_mode=777',
        expectedChecksum: '/srv/upload',
      },
    ],
    database: [
      {
        path: '/opt/scripts/verify_records.js',
        bugVariants: {
          syntax: [
            'const records = [',
            '  { id: 1, status: "active" },',
            '  { id: 2, status: "inactive" },',
            '  { id: 3, status: "active" },',
            '  { id: 4, status: "active" }',
            ']',
            'const active = records.filter(r => r.status === "active")',
            'if (active.length === 3) {',
            '  _system(active.map(r => r.id).join("-")',
            '} else {',
            '  echo("ERROR: record verification failed")',
            '}',
          ].join('\n'),
          logic: [
            'const records = [',
            '  { id: 1, status: "active" },',
            '  { id: 2, status: "inactive" },',
            '  { id: 3, status: "active" },',
            '  { id: 4, status: "active" }',
            ']',
            'const active = records.filter(r => r.status === "inactive")',
            'if (active.length === 3) {',
            '  _system(active.map(r => r.id).join("-"))',
            '} else {',
            '  echo("ERROR: record verification failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const records = [',
            '  { id: 1, status: "active" },',
            '  { id: 2, status: "inactive" },',
            '  { id: 3, status: "???" },',
            '  { id: 4, status: "active" }',
            ']',
            'const active = records.filter(r => r.status === "active")',
            'if (active.length === 3) {',
            '  _system(active.map(r => r.id).join("-"))',
            '} else {',
            '  echo("ERROR: record verification failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.record_data',
        corruptedHintContent: 'record_3_status=active',
        expectedChecksum: '1-3-4',
      },
      {
        path: '/opt/scripts/audit_check.js',
        bugVariants: {
          syntax: [
            'const entries = ["login", "query", "logout", "login", "query"]',
            'const logins = entries.filter(e => e === "login")',
            'const queries = entries.filter(e => e === "query)',
            'if (logins.length === 2 && queries.length === 2) {',
            '  _system(logins.length + "-" + queries.length)',
            '} else {',
            '  echo("ERROR: audit check failed")',
            '}',
          ].join('\n'),
          logic: [
            'const entries = ["login", "query", "logout", "login", "query"]',
            'const logins = entries.filter(e => e === "login")',
            'const queries = entries.filter(e => e === "query")',
            'if (logins.length === 2 && queries.length === 3) {',
            '  _system(logins.length + "-" + queries.length)',
            '} else {',
            '  echo("ERROR: audit check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const entries = ???',
            'const logins = entries.filter(e => e === "login")',
            'const queries = entries.filter(e => e === "query")',
            'if (logins.length === 2 && queries.length === 2) {',
            '  _system(logins.length + "-" + queries.length)',
            '} else {',
            '  echo("ERROR: audit check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.audit_entries',
        corruptedHintContent: 'entries=["login", "query", "logout", "login", "query"]',
        expectedChecksum: '2-2',
      },
      {
        path: '/opt/scripts/check_replication.js',
        bugVariants: {
          syntax: [
            'const nodes = [',
            '  { host: "db-primary", lag: 0 },',
            '  { host: "db-replica1", lag: 120 },',
            '  { host: "db-replica2", lag: 5 },',
            '  { host: "db-replica3", lag: 3 }',
            ']',
            'const healthy = nodes.filter(n => n.lag < 60)',
            'if (healthy.length === 3) {',
            '  _system(healthy.map(n => n.host).join("-"))',
            '} else {',
            '  echo("ERROR: replication check failed")',
            '',
          ].join('\n'),
          logic: [
            'const nodes = [',
            '  { host: "db-primary", lag: 0 },',
            '  { host: "db-replica1", lag: 120 },',
            '  { host: "db-replica2", lag: 5 },',
            '  { host: "db-replica3", lag: 3 }',
            ']',
            'const healthy = nodes.filter(n => n.lag < 60)',
            'if (healthy.length === 4) {',
            '  _system(healthy.map(n => n.host).join("-"))',
            '} else {',
            '  echo("ERROR: replication check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const nodes = [',
            '  { host: "db-primary", lag: 0 },',
            '  { host: "db-replica1", lag: ??? },',
            '  { host: "db-replica2", lag: 5 },',
            '  { host: "db-replica3", lag: 3 }',
            ']',
            'const healthy = nodes.filter(n => n.lag < 60)',
            'if (healthy.length === 3) {',
            '  _system(healthy.map(n => n.host).join("-"))',
            '} else {',
            '  echo("ERROR: replication check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.repl_status',
        corruptedHintContent: 'db-replica1_lag=120',
        expectedChecksum: 'db-primary-db-replica2-db-replica3',
      },
    ],
    webserver: [
      {
        path: '/srv/scripts/check_endpoints.js',
        bugVariants: {
          syntax: [
            'const endpoints = ["/api/users", "/api/health", "/api/admin", "/status"]',
            'const apiRoutes = endpoints.filter(e => e.startsWith("/api/"))',
            'if (apiRoutes.length === 3) {',
            '  _system(apiRoutes.join("-"))',
            ' else {',
            '  echo("ERROR: endpoint check failed")',
            '}',
          ].join('\n'),
          logic: [
            'const endpoints = ["/api/users", "/api/health", "/api/admin", "/status"]',
            'const apiRoutes = endpoints.filter(e => e.startsWith("/api/"))',
            'if (apiRoutes.length === 4) {',
            '  _system(apiRoutes.join("-"))',
            '} else {',
            '  echo("ERROR: endpoint check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const endpoints = ["/api/users", "/api/health", ???, "/status"]',
            'const apiRoutes = endpoints.filter(e => e.startsWith("/api/"))',
            'if (apiRoutes.length === 3) {',
            '  _system(apiRoutes.join("-"))',
            '} else {',
            '  echo("ERROR: endpoint check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/srv/scripts/.endpoint_list',
        corruptedHintContent: 'endpoint_3="/api/admin"',
        expectedChecksum: '/api/users-/api/health-/api/admin',
      },
      {
        path: '/srv/scripts/validate_certs.js',
        bugVariants: {
          syntax: [
            'const certs = ["web.pem", "api.pem", "mail.pem"]',
            'const valid = certs.filter(c => c.endsWith(".pem"))',
            'if (valid.length === 3 {',
            '  _system(valid.join("-"))',
            '} else {',
            '  echo("ERROR: cert validation failed")',
            '}',
          ].join('\n'),
          logic: [
            'const certs = ["web.pem", "api.pem", "mail.pem"]',
            'const valid = certs.filter(c => c.endsWith(".pem"))',
            'if (valid.length === 2) {',
            '  _system(valid.join("-"))',
            '} else {',
            '  echo("ERROR: cert validation failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const certs = ["web.pem", ???, "mail.pem"]',
            'const valid = certs.filter(c => c.endsWith(".pem"))',
            'if (valid.length === 3) {',
            '  _system(valid.join("-"))',
            '} else {',
            '  echo("ERROR: cert validation failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/srv/scripts/.cert_list',
        corruptedHintContent: 'cert_2="api.pem"',
        expectedChecksum: 'web.pem-api.pem-mail.pem',
      },
      {
        path: '/srv/scripts/check_vhosts.js',
        bugVariants: {
          syntax: [
            'const vhosts = [',
            '  { domain: "api.corp.local", port: 443, ssl: true },',
            '  { domain: "staging.corp.local", port: 8080, ssl: false },',
            '  { domain: "www.corp.local", port: 443, ssl: true }',
            ']',
            'const secure = vhosts.filter(v => v.ssl === true && v.port === 443)',
            'if (secure.length === 2) {',
            '  _system(secure.map(v => v.domain).join("-"))',
            '} else {',
            '  echo("ERROR: vhost check failed)',
            '}',
          ].join('\n'),
          logic: [
            'const vhosts = [',
            '  { domain: "api.corp.local", port: 443, ssl: true },',
            '  { domain: "staging.corp.local", port: 8080, ssl: false },',
            '  { domain: "www.corp.local", port: 443, ssl: true }',
            ']',
            'const secure = vhosts.filter(v => v.ssl === true && v.port === 8080)',
            'if (secure.length === 2) {',
            '  _system(secure.map(v => v.domain).join("-"))',
            '} else {',
            '  echo("ERROR: vhost check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const vhosts = [',
            '  { domain: "api.corp.local", port: 443, ssl: true },',
            '  { domain: "staging.corp.local", port: 8080, ssl: ??? },',
            '  { domain: "www.corp.local", port: 443, ssl: true }',
            ']',
            'const secure = vhosts.filter(v => v.ssl === true && v.port === 443)',
            'if (secure.length === 2) {',
            '  _system(secure.map(v => v.domain).join("-"))',
            '} else {',
            '  echo("ERROR: vhost check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/srv/scripts/.vhost_config',
        corruptedHintContent: 'staging_ssl=false',
        expectedChecksum: 'api.corp.local-www.corp.local',
      },
    ],
    workstation: [
      {
        path: '/opt/scripts/verify_access.js',
        bugVariants: {
          syntax: [
            'const users = ["admin", "operator", "analyst", "guest"]',
            'const privileged = users.filter(u => u === "admin" || u === "operator")',
            'if (privileged.length === 2) {',
            '  _system(privileged.join("-"))',
            '} else {',
            '  echo("ERROR: access verification failed)',
            '}',
          ].join('\n'),
          logic: [
            'const users = ["admin", "operator", "analyst", "guest"]',
            'const privileged = users.filter(u => u === "admin")',
            'if (privileged.length === 2) {',
            '  _system(privileged.join("-"))',
            '} else {',
            '  echo("ERROR: access verification failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const users = ["admin", ???, "analyst", "guest"]',
            'const privileged = users.filter(u => u === "admin" || u === "operator")',
            'if (privileged.length === 2) {',
            '  _system(privileged.join("-"))',
            '} else {',
            '  echo("ERROR: access verification failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.user_list',
        corruptedHintContent: 'user_2="operator"',
        expectedChecksum: 'admin-operator',
      },
      {
        path: '/opt/scripts/check_projects.js',
        bugVariants: {
          syntax: [
            'const projects = [',
            '  { name: "alpha", priority: "high" },',
            '  { name: "beta", priority: "low" },',
            '  { name: "gamma", priority: "high" }',
            ']',
            'const urgent = projects.filter(p => p.priority === "high")',
            'if (urgent.length === 2) {',
            '  _system(urgent.map(p => p.name).join("-")',
            '} else {',
            '  echo("ERROR: project check failed")',
            '}',
          ].join('\n'),
          logic: [
            'const projects = [',
            '  { name: "alpha", priority: "high" },',
            '  { name: "beta", priority: "low" },',
            '  { name: "gamma", priority: "high" }',
            ']',
            'const urgent = projects.filter(p => p.priority === "low")',
            'if (urgent.length === 2) {',
            '  _system(urgent.map(p => p.name).join("-"))',
            '} else {',
            '  echo("ERROR: project check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const projects = [',
            '  { name: "alpha", priority: "high" },',
            '  { name: "beta", priority: ??? },',
            '  { name: "gamma", priority: "high" }',
            ']',
            'const urgent = projects.filter(p => p.priority === "high")',
            'if (urgent.length === 2) {',
            '  _system(urgent.map(p => p.name).join("-"))',
            '} else {',
            '  echo("ERROR: project check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.project_data',
        corruptedHintContent: 'beta_priority="low"',
        expectedChecksum: 'alpha-gamma',
      },
      {
        path: '/opt/scripts/scan_ports.js',
        bugVariants: {
          syntax: [
            'const services = [',
            '  { port: 22, state: "open", svc: "ssh" },',
            '  { port: 80, state: "closed", svc: "http" },',
            '  { port: 443, state: "open", svc: "https" },',
            '  { port: 3306, state: "open", svc: "mysql" }',
            ']',
            'const exposed = services.filter(s => s.state === "open")',
            'if (exposed.length === 3 {',
            '  _system(exposed.map(s => s.svc).join("-"))',
            '} else {',
            '  echo("ERROR: port scan failed")',
            '}',
          ].join('\n'),
          logic: [
            'const services = [',
            '  { port: 22, state: "open", svc: "ssh" },',
            '  { port: 80, state: "closed", svc: "http" },',
            '  { port: 443, state: "open", svc: "https" },',
            '  { port: 3306, state: "open", svc: "mysql" }',
            ']',
            'const exposed = services.filter(s => s.state === "closed")',
            'if (exposed.length === 3) {',
            '  _system(exposed.map(s => s.svc).join("-"))',
            '} else {',
            '  echo("ERROR: port scan failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const services = [',
            '  { port: 22, state: "open", svc: "ssh" },',
            '  { port: 80, state: ???, svc: "http" },',
            '  { port: 443, state: "open", svc: "https" },',
            '  { port: 3306, state: "open", svc: "mysql" }',
            ']',
            'const exposed = services.filter(s => s.state === "open")',
            'if (exposed.length === 3) {',
            '  _system(exposed.map(s => s.svc).join("-"))',
            '} else {',
            '  echo("ERROR: port scan failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.port_scan',
        corruptedHintContent: 'port_80_state="closed"',
        expectedChecksum: 'ssh-https-mysql',
      },
    ],
    iot: [
      {
        path: '/opt/scripts/check_sensors.js',
        bugVariants: {
          syntax: [
            'const readings = [22.5, 25.1, 18.3, 24.7, 19.8]',
            'const normal = readings.filter(r => r >= 18 && r <= 25)',
            'if (normal.length === 4) {',
            '  _system(normal.join("-")',
            '} else {',
            '  echo("ERROR: sensor check failed")',
            '}',
          ].join('\n'),
          logic: [
            'const readings = [22.5, 25.1, 18.3, 24.7, 19.8]',
            'const normal = readings.filter(r => r >= 18 && r <= 25)',
            'if (normal.length === 5) {',
            '  _system(normal.join("-"))',
            '} else {',
            '  echo("ERROR: sensor check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const readings = [22.5, ???, 18.3, 24.7, 19.8]',
            'const normal = readings.filter(r => r >= 18 && r <= 25)',
            'if (normal.length === 4) {',
            '  _system(normal.join("-"))',
            '} else {',
            '  echo("ERROR: sensor check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.sensor_log',
        corruptedHintContent: 'reading_2=25.1',
        expectedChecksum: '22.5-18.3-24.7-19.8',
      },
      {
        path: '/opt/scripts/device_health.js',
        bugVariants: {
          syntax: [
            'const devices = [',
            '  { name: "cam-01", status: "online" },',
            '  { name: "cam-02", status: "offline" },',
            '  { name: "cam-03", status: "online" }',
            ']',
            'const active = devices.filter(d => d.status === "online")',
            'if (active.length === 2) {',
            '  _system(active.map(d => d.name).join("-"))',
            '} else {',
            '  echo("ERROR: device health check failed")',
            '',
          ].join('\n'),
          logic: [
            'const devices = [',
            '  { name: "cam-01", status: "online" },',
            '  { name: "cam-02", status: "offline" },',
            '  { name: "cam-03", status: "online" }',
            ']',
            'const active = devices.filter(d => d.status === "offline")',
            'if (active.length === 2) {',
            '  _system(active.map(d => d.name).join("-"))',
            '} else {',
            '  echo("ERROR: device health check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const devices = [',
            '  { name: "cam-01", status: "online" },',
            '  { name: "cam-02", status: ??? },',
            '  { name: "cam-03", status: "online" }',
            ']',
            'const active = devices.filter(d => d.status === "online")',
            'if (active.length === 2) {',
            '  _system(active.map(d => d.name).join("-"))',
            '} else {',
            '  echo("ERROR: device health check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.device_status',
        corruptedHintContent: 'cam-02_status="offline"',
        expectedChecksum: 'cam-01-cam-03',
      },
      {
        path: '/opt/scripts/check_firmware.js',
        bugVariants: {
          syntax: [
            'const devices = [',
            '  { id: "gw-01", ver: "2.1.4", latest: "2.1.4" },',
            '  { id: "cam-01", ver: "1.0.3", latest: "1.2.0" },',
            '  { id: "therm-01", ver: "3.0.0", latest: "3.0.0" }',
            ']',
            'const outdated = devices.filter(d => d.ver !== d.latest',
            'if (outdated.length === 1) {',
            '  _system(outdated.map(d => d.id + ":" + d.ver).join("-"))',
            '} else {',
            '  echo("ERROR: firmware check failed")',
            '}',
          ].join('\n'),
          logic: [
            'const devices = [',
            '  { id: "gw-01", ver: "2.1.4", latest: "2.1.4" },',
            '  { id: "cam-01", ver: "1.0.3", latest: "1.2.0" },',
            '  { id: "therm-01", ver: "3.0.0", latest: "3.0.0" }',
            ']',
            'const outdated = devices.filter(d => d.ver === d.latest)',
            'if (outdated.length === 1) {',
            '  _system(outdated.map(d => d.id + ":" + d.ver).join("-"))',
            '} else {',
            '  echo("ERROR: firmware check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const devices = [',
            '  { id: "gw-01", ver: "2.1.4", latest: "2.1.4" },',
            '  { id: "cam-01", ver: ???, latest: "1.2.0" },',
            '  { id: "therm-01", ver: "3.0.0", latest: "3.0.0" }',
            ']',
            'const outdated = devices.filter(d => d.ver !== d.latest)',
            'if (outdated.length === 1) {',
            '  _system(outdated.map(d => d.id + ":" + d.ver).join("-"))',
            '} else {',
            '  echo("ERROR: firmware check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.firmware_versions',
        corruptedHintContent: 'cam-01_ver="1.0.3"',
        expectedChecksum: 'cam-01:1.0.3',
      },
    ],
    mailserver: [
      {
        path: '/opt/scripts/filter_spam.js',
        bugVariants: {
          syntax: [
            'const messages = ["inbox", "spam", "inbox", "spam", "spam"]',
            'const spam = messages.filter(m => m === "spam")',
            'if (spam.length === 3) {',
            '  _system(spam.join("-")',
            '} else {',
            '  echo("ERROR: spam filter check failed")',
            '}',
          ].join('\n'),
          logic: [
            'const messages = ["inbox", "spam", "inbox", "spam", "spam"]',
            'const spam = messages.filter(m => m === "spam")',
            'if (spam.length === 2) {',
            '  _system(spam.join("-"))',
            '} else {',
            '  echo("ERROR: spam filter check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const messages = ["inbox", ???, "inbox", "spam", "spam"]',
            'const spam = messages.filter(m => m === "spam")',
            'if (spam.length === 3) {',
            '  _system(spam.join("-"))',
            '} else {',
            '  echo("ERROR: spam filter check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.message_log',
        corruptedHintContent: 'message_2="spam"',
        expectedChecksum: 'spam-spam-spam',
      },
      {
        path: '/opt/scripts/validate_mailboxes.js',
        bugVariants: {
          syntax: [
            'const mailboxes = [',
            '  { user: "admin", quota: "full" },',
            '  { user: "ceo", quota: "ok" },',
            '  { user: "hr", quota: "full" }',
            ']',
            'const overQuota = mailboxes.filter(m => m.quota === "full")',
            'if (overQuota.length === 2) {',
            '  _system(overQuota.map(m => m.user).join("-"))',
            '} else {',
            '  echo("ERROR: mailbox validation failed")',
            '',
          ].join('\n'),
          logic: [
            'const mailboxes = [',
            '  { user: "admin", quota: "full" },',
            '  { user: "ceo", quota: "ok" },',
            '  { user: "hr", quota: "full" }',
            ']',
            'const overQuota = mailboxes.filter(m => m.quota === "ok")',
            'if (overQuota.length === 2) {',
            '  _system(overQuota.map(m => m.user).join("-"))',
            '} else {',
            '  echo("ERROR: mailbox validation failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const mailboxes = [',
            '  { user: "admin", quota: "full" },',
            '  { user: "ceo", quota: ??? },',
            '  { user: "hr", quota: "full" }',
            ']',
            'const overQuota = mailboxes.filter(m => m.quota === "full")',
            'if (overQuota.length === 2) {',
            '  _system(overQuota.map(m => m.user).join("-"))',
            '} else {',
            '  echo("ERROR: mailbox validation failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.mailbox_status',
        corruptedHintContent: 'ceo_quota="ok"',
        expectedChecksum: 'admin-hr',
      },
      {
        path: '/opt/scripts/check_queues.js',
        bugVariants: {
          syntax: [
            'const queues = [',
            '  { name: "inbox", count: 142 },',
            '  { name: "outbox", count: 0 },',
            '  { name: "deferred", count: 37 },',
            '  { name: "bounce", count: 8 }',
            ']',
            'const stuck = queues.filter(q => q.count > 0 && q.name !== "inbox")',
            'if (stuck.length === 2) {',
            '  _system(stuck.map(q => q.name + ":" + q.count).join("-"))',
            '} else {',
            '  echo("ERROR: queue check failed")',
            '',
          ].join('\n'),
          logic: [
            'const queues = [',
            '  { name: "inbox", count: 142 },',
            '  { name: "outbox", count: 0 },',
            '  { name: "deferred", count: 37 },',
            '  { name: "bounce", count: 8 }',
            ']',
            'const stuck = queues.filter(q => q.count > 0 && q.name !== "inbox")',
            'if (stuck.length === 3) {',
            '  _system(stuck.map(q => q.name + ":" + q.count).join("-"))',
            '} else {',
            '  echo("ERROR: queue check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const queues = [',
            '  { name: "inbox", count: 142 },',
            '  { name: "outbox", count: ??? },',
            '  { name: "deferred", count: 37 },',
            '  { name: "bounce", count: 8 }',
            ']',
            'const stuck = queues.filter(q => q.count > 0 && q.name !== "inbox")',
            'if (stuck.length === 2) {',
            '  _system(stuck.map(q => q.name + ":" + q.count).join("-"))',
            '} else {',
            '  echo("ERROR: queue check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.queue_status',
        corruptedHintContent: 'outbox_count=0',
        expectedChecksum: 'deferred:37-bounce:8',
      },
    ],
    dns: [
      {
        path: '/srv/scripts/check_zones.js',
        bugVariants: {
          syntax: [
            'const zones = ["mission", "internal", "reverse", "cache"]',
            'const active = zones.filter(z => z !== "cache")',
            'if (active.length === 3 {',
            '  _system(active.join("-"))',
            '} else {',
            '  echo("ERROR: zone validation failed")',
            '}',
          ].join('\n'),
          logic: [
            'const zones = ["mission", "internal", "reverse", "cache"]',
            'const active = zones.filter(z => z !== "cache")',
            'if (active.length === 4) {',
            '  _system(active.join("-"))',
            '} else {',
            '  echo("ERROR: zone validation failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const zones = ???',
            'const active = zones.filter(z => z !== "cache")',
            'if (active.length === 3) {',
            '  _system(active.join("-"))',
            '} else {',
            '  echo("ERROR: zone validation failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/srv/scripts/.zone_list',
        corruptedHintContent: 'zones=["mission", "internal", "reverse", "cache"]',
        expectedChecksum: 'mission-internal-reverse',
      },
      {
        path: '/srv/scripts/dns_health.js',
        bugVariants: {
          syntax: [
            'const records = [',
            '  { type: "A", count: 24 },',
            '  { type: "CNAME", count: 6 },',
            '  { type: "PTR", count: 12 }',
            ']',
            'const valid = records.filter(r => r.count > 0',
            'if (valid.length === 3) {',
            '  _system(valid.map(r => r.type + ":" + r.count).join("-"))',
            '} else {',
            '  echo("ERROR: DNS health check failed")',
            '}',
          ].join('\n'),
          logic: [
            'const records = [',
            '  { type: "A", count: 24 },',
            '  { type: "CNAME", count: 6 },',
            '  { type: "PTR", count: 12 }',
            ']',
            'const valid = records.filter(r => r.count > 5)',
            'if (valid.length === 3) {',
            '  _system(valid.map(r => r.type + ":" + r.count).join("-"))',
            '} else {',
            '  echo("ERROR: DNS health check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const records = [',
            '  { type: "A", count: ??? },',
            '  { type: "CNAME", count: 6 },',
            '  { type: "PTR", count: 12 }',
            ']',
            'const valid = records.filter(r => r.count > 0)',
            'if (valid.length === 3) {',
            '  _system(valid.map(r => r.type + ":" + r.count).join("-"))',
            '} else {',
            '  echo("ERROR: DNS health check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/srv/scripts/.record_counts',
        corruptedHintContent: 'a_records=24',
        expectedChecksum: 'A:24-CNAME:6-PTR:12',
      },
    ],
    // Router is infrastructure-only (never the mission target), but the type system
    // requires templates for every role. These are unused in practice.
    router: [
      {
        path: '/opt/scripts/check_routes.js',
        bugVariants: {
          syntax: [
            'const routes = ["10.0.0.0/24", "172.16.0.0/16", "192.168.1.0/24"]',
            'const internal = routes.filter(r => r.startsWith("10.") || r.startsWith("172.")',
            'if (internal.length === 2) {',
            '  _system(internal.join("-"))',
            '} else {',
            '  echo("ERROR: route check failed")',
            '}',
          ].join('\n'),
          logic: [
            'const routes = ["10.0.0.0/24", "172.16.0.0/16", "192.168.1.0/24"]',
            'const internal = routes.filter(r => r.startsWith("10.") || r.startsWith("172."))',
            'if (internal.length === 3) {',
            '  _system(internal.join("-"))',
            '} else {',
            '  echo("ERROR: route check failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const routes = [???, "172.16.0.0/16", "192.168.1.0/24"]',
            'const internal = routes.filter(r => r.startsWith("10.") || r.startsWith("172."))',
            'if (internal.length === 2) {',
            '  _system(internal.join("-"))',
            '} else {',
            '  echo("ERROR: route check failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.route_config',
        corruptedHintContent: 'route_1="10.0.0.0/24"',
        expectedChecksum: '10.0.0.0/24-172.16.0.0/16',
      },
      {
        path: '/opt/scripts/verify_firewall.js',
        bugVariants: {
          syntax: [
            'const rules = ["ACCEPT", "DROP", "ACCEPT", "ACCEPT"]',
            'const allowed = rules.filter(r => r === "ACCEPT")',
            'if (allowed.length === 3) {',
            '  _system(allowed.join("-"))',
            '} else {',
            '  echo("ERROR: firewall verification failed)',
            '}',
          ].join('\n'),
          logic: [
            'const rules = ["ACCEPT", "DROP", "ACCEPT", "ACCEPT"]',
            'const allowed = rules.filter(r => r === "DROP")',
            'if (allowed.length === 3) {',
            '  _system(allowed.join("-"))',
            '} else {',
            '  echo("ERROR: firewall verification failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const rules = ["ACCEPT", ???, "ACCEPT", "ACCEPT"]',
            'const allowed = rules.filter(r => r === "ACCEPT")',
            'if (allowed.length === 3) {',
            '  _system(allowed.join("-"))',
            '} else {',
            '  echo("ERROR: firewall verification failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.fw_rules',
        corruptedHintContent: 'rule_2="DROP"',
        expectedChecksum: 'ACCEPT-ACCEPT-ACCEPT',
      },
    ],
    // Switch is infrastructure-only (never the mission target), but the type system
    // requires script fix templates for every role. These are unused in practice.
    switch: [
      {
        path: '/opt/scripts/check_acls.js',
        bugVariants: {
          syntax: [
            'const acls = ["allow", "deny", "allow", "allow"]',
            'const allowed = acls.filter(a => a === "allow")',
            'if (allowed.length === 3) {',
            '  _system(allowed.join("-"))',
            '} else {',
            '  echo("ERROR: ACL verification failed)',
            '}',
          ].join('\n'),
          logic: [
            'const acls = ["allow", "deny", "allow", "allow"]',
            'const allowed = acls.filter(a => a === "deny")',
            'if (allowed.length === 3) {',
            '  _system(allowed.join("-"))',
            '} else {',
            '  echo("ERROR: ACL verification failed")',
            '}',
          ].join('\n'),
          corrupted: [
            'const acls = ["allow", ???, "allow", "allow"]',
            'const allowed = acls.filter(a => a === "allow")',
            'if (allowed.length === 3) {',
            '  _system(allowed.join("-"))',
            '} else {',
            '  echo("ERROR: ACL verification failed")',
            '}',
          ].join('\n'),
        },
        corruptedHintPath: '/opt/scripts/.acl_rules',
        corruptedHintContent: 'rule_2="deny"',
        expectedChecksum: 'allow-allow-allow',
      },
    ],
  };
