/**
 * The commands a person typed, as their `.bash_history` remembers them — minus the
 * network lines, which are built in code from the box's real neighbours so that every
 * host, account and port a history names is one that truly answers.
 *
 * These are the local half: what a person does on their own machine. Rules the tests
 * hold the output to, and the reason the pool is written the way it is:
 * - **Every absolute or home path is one the box has.** A home carries `~`, `~/notes`
 *   and the dotfiles; every box carries `/etc/passwd`, `/var/log/auth.log` and `/tmp`.
 *   A line names only those. A line that opens a note does it through the `{note}` slot,
 *   which the builder fills with a note this home actually holds. A bare relative name
 *   like `deploy.sh` names nothing under `~` or `/`, so replaying it opens a new file
 *   rather than a missing one.
 * - **No network verb.** `ssh`, `curl`, `ping` and `nslookup` lines are generated from
 *   the real LAN, never templated, so a template can never name a host that is not there.
 * - **No decimal.** A version dates a box and nothing else in the world carries one; the
 *   test that forbids versions reads any bare `1.2` as one, so no `-V`, no `==2`, no `.0`.
 *
 * Slots: `{first}` the inhabitant's first name, `{colleague}` someone they know,
 * `{count}` a small number, `{note}` the name of a note this home actually has.
 */

/** Lines any person types, whatever the network is. */
export const PERSONAL_HISTORY: readonly string[] = [
  'ls -la',
  'll',
  'cd ~',
  'clear',
  'pwd',
  'whoami',
  'df -h',
  'free -m',
  'uptime',
  'history',
  'htop',
  'ps aux',
  'cat ~/notes/{note}',
  'ls ~/notes',
  'vim ~/notes/{note}',
  'nano ~/.bashrc',
  'cat ~/.bashrc',
  'source ~/.bashrc',
  'vim ~/.gitconfig',
  'cat /etc/passwd',
  'tail /var/log/auth.log',
  'cd /tmp',
  'ls /tmp',
  'git status',
  'git log --oneline',
  'git pull',
  'git diff',
  'git add -A',
  "git commit -m 'wip'",
  'git push',
  'python3',
  'exit',
  'sudo apt update',
  'sudo apt upgrade',
  'man bash',
  'ssh-keygen -t ed25519',
  'cat ~/.bash_history',
  'chmod +x deploy.sh',
  'crontab -l',
  'du -sh *',
  'env',
  'which python3',
  'jobs',
  'echo $PATH',
  'type ll',
  'tar -czf backup.tgz notes',
  'less /etc/passwd',
  'wc -l ~/.bash_history',
  'grep alias ~/.bashrc',
  'diff ~/.bashrc ~/.profile',
  'touch ~/notes/{note}',
  'mkdir -p projects',
];

/** Lines flavoured by the kind of place the network is — still local, still safe. */
export const WORK_HISTORY: Readonly<Record<string, readonly string[]>> = {
  corporate: [
    'vim ~/notes/{note}',
    'git checkout -b feature/reporting',
    "git commit -m 'address review from {colleague}'",
    'make test',
    'make build',
    'docker ps',
    'docker compose up -d',
    'kubectl get pods',
    'terraform plan',
    'npm run lint',
    'cat ~/notes/{note}',
    'grep -r TODO src/',
    'tail -f app.log',
    './deploy.sh staging',
  ],
  cafe: [
    'cat ~/notes/{note}',
    'vim ~/notes/{note}',
    'python3 till.py',
    'lp receipt.txt',
    'll ~/notes',
    'echo "back soon" > sign.txt',
    'cat sign.txt',
    'nano ~/notes/{note}',
    'wc -l ~/notes/{note}',
    'date',
    'cal',
    'sort orders.txt',
    'clear',
    'exit',
  ],
  residential: [
    'cat ~/notes/{note}',
    'vim ~/notes/{note}',
    'python3',
    'firefox &',
    'll',
    'echo "{colleague} owes {count}" >> ~/notes/{note}',
    'nano ~/notes/{note}',
    'du -sh downloads',
    'ls downloads',
    'mpv playlist.m3u',
    'date',
    'cal',
    'clear',
    'exit',
  ],
  university: [
    'cat ~/notes/{note}',
    'vim thesis.tex',
    'pdflatex thesis.tex',
    'python3 analyse.py',
    'jupyter notebook',
    'git pull',
    "git commit -m 'results for {colleague}'",
    'grep -r references ~/notes',
    'make',
    './run_experiment.sh',
    'vim ~/notes/{note}',
    'wc -w thesis.tex',
    'tmux attach',
    'clear',
  ],
  public: [
    'cat ~/notes/{note}',
    'vim ~/notes/{note}',
    'firefox &',
    'lp application.txt',
    'll',
    'python3',
    'nano ~/notes/{note}',
    'date',
    'cal',
    'echo done >> ~/notes/{note}',
    'wc -l ~/notes/{note}',
    'clear',
    'history | tail',
    'exit',
  ],
  iot: [
    'cat ~/notes/{note}',
    'vim ~/notes/{note}',
    'python3 sensor.py',
    'tail -f device.log',
    'll',
    'systemctl status home-hub',
    'journalctl -u home-hub',
    'nano ~/notes/{note}',
    'mosquitto_sub -t home',
    'date',
    'clear',
    'reboot',
    'dmesg | tail',
    'exit',
  ],
  hacker: [
    'cat ~/notes/{note}',
    'vim ~/notes/{note}',
    'make flash',
    'python3 badge.py',
    'gcc firmware.c -o firmware',
    'minicom',
    "git commit -m 'fix for {colleague}'",
    'll',
    'screen ttyUSB0',
    'nano ~/notes/{note}',
    'tmux new -s ctf',
    'clear',
    'dmesg',
    'exit',
  ],
};
