/**
 * What a department share holds, by the kind of place it serves.
 *
 * Each kind of place keeps its own departments, and each department its own files: a
 * café's share holds menus and rotas, a family's NAS its paperwork and photos. The
 * names and bodies are authored, never drawn letter by letter, so every one reads as
 * something a person saved. Nothing here names a credential or a version: a share is
 * where an organisation keeps its work, not its keys, and a version would date the box.
 *
 * A text body is a template. Its slots are filled when the share is built, so the same
 * note on two networks is written by two different people about two different places:
 *
 *   {place}   what the network's people call where they are ("the café")
 *   {person}  the full name of one of the network's people, drawn afresh each time
 *   {first}   the first name of one of them, drawn afresh each time
 *   {date}    the day the file was first saved, as YYYY-MM-DD
 *   {number}  a small count
 *   {amount}  a sum of money, in whole units
 *
 * Every body carries at least one slot that differs from box to box, so two shares on
 * one network never hold the same note byte for byte.
 */

import type { NetworkCategory } from './essidCatalog';

export type ShareFileSpec =
  | { readonly name: string; readonly format: 'pdf'; readonly title: string }
  | { readonly name: string; readonly format: 'jpeg' }
  | { readonly name: string; readonly format: 'docx' | 'xlsx' }
  | { readonly name: string; readonly format: 'text'; readonly body: string };

type Folders = Readonly<Record<string, readonly ShareFileSpec[]>>;

const pdf = (name: string, title: string): ShareFileSpec => ({ name, format: 'pdf', title });
const photo = (name: string): ShareFileSpec => ({ name, format: 'jpeg' });
const docx = (name: string): ShareFileSpec => ({ name, format: 'docx' });
const xlsx = (name: string): ShareFileSpec => ({ name, format: 'xlsx' });
const text = (name: string, lines: readonly string[]): ShareFileSpec => ({
  name,
  format: 'text',
  body: `${lines.join('\n')}\n`,
});

export const SHARE_FOLDERS: Readonly<Record<NetworkCategory, Folders>> = {
  corporate: {
    finance: [
      pdf('q2-budget.pdf', 'Q2 budget'),
      pdf('annual-accounts.pdf', 'Annual accounts'),
      pdf('audit-letter.pdf', 'Letter from the auditors'),
      xlsx('expenses-march.xlsx'),
      xlsx('cashflow-forecast.xlsx'),
      xlsx('payroll-summary.xlsx'),
      docx('spending-approval.docx'),
      text('invoice-log.csv', [
        'date,supplier,amount,approved_by',
        '{date},Office supplies,{amount},{person}',
        '{date},Cleaning contract,{amount},{person}',
        '{date},Couriers,{amount},{person}',
      ]),
      text('month-end.txt', [
        'Month end checklist, started {date}',
        '- bank reconciliation: {first}',
        '- accruals: {first}',
        '- sign-off: {person}',
      ]),
      text('README.md', [
        '# Finance',
        '',
        'Approved figures only. Drafts stay on your own machine.',
        'Questions to {person}.',
      ]),
    ],
    hr: [
      pdf('holiday-policy.pdf', 'Holiday policy'),
      pdf('org-chart.pdf', 'Organisation chart'),
      pdf('code-of-conduct.pdf', 'Code of conduct'),
      pdf('parental-leave.pdf', 'Parental leave policy'),
      docx('onboarding-checklist.docx'),
      docx('job-description-template.docx'),
      xlsx('headcount.xlsx'),
      xlsx('training-log.xlsx'),
      text('new-starters.csv', [
        'start_date,name,team,buddy',
        '{date},{person},Operations,{person}',
        '{date},{person},Sales,{person}',
      ]),
      text('interview-rota.txt', [
        'Interview panel from {date}',
        'Morning: {person} and {person}',
        'Afternoon: {person}',
      ]),
    ],
    legal: [
      pdf('supplier-contract.pdf', 'Supplier contract'),
      pdf('lease.pdf', 'Office lease'),
      pdf('privacy-notice.pdf', 'Privacy notice'),
      pdf('terms-of-business.pdf', 'Terms of business'),
      docx('nda-template.docx'),
      docx('contract-review.docx'),
      xlsx('contract-register.xlsx'),
      text('README.md', [
        '# Legal',
        '',
        'Signed copies only. Anything with a red line goes to {person} first.',
      ]),
      text('renewals.txt', [
        'Renewals due, as of {date}',
        'Lease: talk to the landlord before the break clause',
        'Insurance: {person} has the broker details',
      ]),
      text('trademark-notes.md', [
        '# Trademark',
        '',
        'Filed {date}. {person} is handling the objection.',
      ]),
    ],
    sales: [
      pdf('price-list.pdf', 'Price list'),
      pdf('case-study.pdf', 'Customer case study'),
      pdf('proposal-template.pdf', 'Proposal template'),
      xlsx('pipeline.xlsx'),
      xlsx('targets.xlsx'),
      xlsx('commission.xlsx'),
      docx('pitch-notes.docx'),
      photo('trade-show.jpg'),
      text('leads.csv', [
        'date,company,owner,stage',
        '{date},Harbour Freight,{person},qualified',
        '{date},Northgate Dental,{person},proposal',
        '{date},Lakeside Hotels,{person},won',
      ]),
      text('call-notes.txt', [
        'Call with the regional buyer, {date}',
        'They want {number} units before the summer.',
        'Follow up: {first}',
      ]),
    ],
    it: [
      pdf('acceptable-use.pdf', 'Acceptable use policy'),
      pdf('laptop-handover.pdf', 'Laptop handover form'),
      pdf('backup-procedure.pdf', 'Backup procedure'),
      xlsx('asset-register.xlsx'),
      xlsx('licence-renewals.xlsx'),
      docx('new-starter-setup.docx'),
      text('printer-setup.txt', [
        'Adding the second floor printer',
        'Settings, Printers, Add. It shows up by itself.',
        'Still stuck? Ask {first}. Updated {date}.',
      ]),
      text('rack-layout.md', [
        '# Rack',
        '',
        'Top: switch. Middle: the file server. Bottom: the UPS.',
        'Last checked {date} by {person}.',
      ]),
      text('tickets.csv', [
        'opened,raised_by,summary',
        '{date},{person},Monitor flickers',
        '{date},{person},Cannot print double sided',
        '{date},{person},Headset not detected',
      ]),
      text('oncall.txt', ['Out of hours cover from {date}', 'Week one: {person}', 'Week two: {person}']),
    ],
    marketing: [
      pdf('brand-guidelines.pdf', 'Brand guidelines'),
      pdf('media-kit.pdf', 'Media kit'),
      pdf('campaign-report.pdf', 'Campaign report'),
      photo('launch-photo.jpg'),
      photo('team-photo.jpg'),
      photo('stand-setup.jpg'),
      docx('newsletter-draft.docx'),
      docx('press-release.docx'),
      xlsx('social-calendar.xlsx'),
      text('taglines.txt', [
        'Tagline ideas, {date}',
        '- Built properly, the first time',
        '- Closer than you think',
        'Pick one by Friday. {first}',
      ]),
    ],
    facilities: [
      pdf('fire-drill.pdf', 'Fire drill procedure'),
      pdf('desk-plan.pdf', 'Desk plan'),
      pdf('first-aid.pdf', 'First aid arrangements'),
      pdf('lift-inspection.pdf', 'Lift inspection certificate'),
      xlsx('maintenance-log.xlsx'),
      docx('visitor-procedure.docx'),
      photo('kitchen-leak.jpg'),
      text('cleaning-rota.csv', [
        'week_of,area,who',
        '{date},kitchen,{person}',
        '{date},meeting rooms,{person}',
      ]),
      text('keys.txt', [
        'Who holds a key to {place}, as of {date}',
        '{person}',
        '{person}',
        '{person}',
      ]),
      text('parking.md', [
        '# Parking',
        '',
        'There are {number} spaces. Ask {first} for a permit.',
      ]),
    ],
  },
  cafe: {
    menus: [
      pdf('spring-menu.pdf', 'Spring menu'),
      pdf('winter-menu.pdf', 'Winter menu'),
      pdf('allergens.pdf', 'Allergen information'),
      pdf('drinks-list.pdf', 'Drinks list'),
      docx('specials.docx'),
      docx('catering-menu.docx'),
      xlsx('recipe-costings.xlsx'),
      text('specials-board.txt', [
        'Board for {date}',
        'Soup: roast tomato',
        'Cake: whatever {first} bakes',
      ]),
      text('menu-ideas.md', [
        '# Next menu',
        '',
        'Lose the panini, keep the toasties. {first} wants a vegan breakfast.',
        'Started {date}.',
      ]),
      text('price-changes.csv', [
        'from,item,price',
        '{date},flat white,{number}',
        '{date},scone,{number}',
      ]),
    ],
    rota: [
      xlsx('rota.xlsx'),
      xlsx('hours-worked.xlsx'),
      pdf('staff-handbook.pdf', 'Staff handbook'),
      docx('opening-checklist.docx'),
      docx('closing-checklist.docx'),
      text('rota-this-week.csv', [
        'week_of,open,close',
        '{date},{person},{person}',
        '{date},{person},{person}',
      ]),
      text('holiday-requests.txt', [
        'Holiday requests from {date}',
        '{first}: a week in August',
        '{first}: two days at half term',
      ]),
      text('swaps.txt', ['Shift swaps, week of {date}', '{first} covers {first} on Saturday']),
      text('training.md', [
        '# Barista training',
        '',
        '{person} signs off the milk steaming. Started {date}.',
      ]),
      text('cover.txt', ['Sick cover list, {date}', '{person}', '{person}']),
    ],
    suppliers: [
      xlsx('suppliers.xlsx'),
      xlsx('price-comparison.xlsx'),
      pdf('milk-order.pdf', 'Standing milk order'),
      pdf('coffee-contract.pdf', 'Coffee supply agreement'),
      pdf('bakery-terms.pdf', 'Bakery terms'),
      docx('complaint-letter.docx'),
      text('contacts.txt', [
        'Suppliers for {place}',
        'Bakery delivers before seven. Ask for {first}.',
        'Updated {date}',
      ]),
      text('order-log.csv', [
        'date,supplier,cost',
        '{date},Coffee roaster,{amount}',
        '{date},Dairy,{amount}',
      ]),
      text('deliveries.md', [
        '# Deliveries',
        '',
        'Round the back, never the front door. {first} signs for them.',
        'Noted {date}.',
      ]),
      text('returns.txt', ['Short delivery on {date}: {number} loaves', 'Credit note chased by {first}']),
    ],
    invoices: [
      pdf('invoice-0412.pdf', 'Invoice'),
      pdf('invoice-0419.pdf', 'Invoice'),
      pdf('invoice-0426.pdf', 'Invoice'),
      pdf('invoice-0503.pdf', 'Invoice'),
      pdf('catering-invoice.pdf', 'Catering invoice'),
      pdf('credit-note.pdf', 'Credit note'),
      xlsx('takings.xlsx'),
      xlsx('vat-quarter.xlsx'),
      text('unpaid.csv', ['date,customer,amount', '{date},Office lunch order,{amount}']),
      text('banking.txt', ['Banked on {date}: {amount}', 'Paid in by {first}']),
    ],
    inspections: [
      pdf('hygiene-report.pdf', 'Food hygiene inspection'),
      pdf('fire-risk.pdf', 'Fire risk assessment'),
      pdf('gas-safety.pdf', 'Gas safety certificate'),
      pdf('pest-control.pdf', 'Pest control visit'),
      docx('cleaning-schedule.docx'),
      docx('allergen-training.docx'),
      xlsx('temperature-log.xlsx'),
      photo('extractor-fan.jpg'),
      text('fridge-temps.csv', ['date,fridge,temp_c,checked_by', '{date},display,{number},{person}']),
      text('actions.txt', [
        'From the inspection on {date}',
        '- new seal on the walk-in door',
        '- label the dates on everything. {first}',
      ]),
    ],
    photos: [
      photo('counter.jpg'),
      photo('new-sign.jpg'),
      photo('latte-art.jpg'),
      photo('cake-stand.jpg'),
      photo('terrace.jpg'),
      photo('opening-day.jpg'),
      photo('team-night-out.jpg'),
      photo('window-display.jpg'),
      photo('brunch.jpg'),
      photo('delivery-van.jpg'),
    ],
  },
  residential: {
    paperwork: [
      pdf('tenancy-agreement.pdf', 'Tenancy agreement'),
      pdf('car-insurance.pdf', 'Car insurance schedule'),
      pdf('home-insurance.pdf', 'Home insurance policy'),
      pdf('council-tax.pdf', 'Council tax bill'),
      pdf('energy-bill.pdf', 'Energy bill'),
      pdf('broadband-contract.pdf', 'Broadband contract'),
      docx('complaint-to-landlord.docx'),
      xlsx('household-budget.xlsx'),
      text('passport-renewal.txt', [
        'Passport renewal for {first}, started {date}',
        'Photos, form, old passport.',
      ]),
      text('where-things-are.md', [
        '# Where things are',
        '',
        'Stopcock under the sink. Fuse box in the hall cupboard.',
        'Written up by {first} on {date}.',
      ]),
    ],
    taxes: [
      pdf('tax-return.pdf', 'Tax return'),
      pdf('p60.pdf', 'End of year certificate'),
      pdf('pension-statement.pdf', 'Pension statement'),
      pdf('charity-receipts.pdf', 'Charity receipts'),
      xlsx('receipts.xlsx'),
      xlsx('mileage.xlsx'),
      docx('accountant-letter.docx'),
      text('notes.txt', ['Ask about the home office, {date}', '{first} has the receipts']),
      text('deadlines.md', ['# Deadlines', '', 'Return filed {date}. Next one in January.']),
      text('expenses.csv', ['date,item,amount', '{date},desk chair,{amount}', '{date},train fares,{amount}']),
    ],
    house: [
      pdf('boiler-manual.pdf', 'Boiler manual'),
      pdf('kitchen-quote.pdf', 'Kitchen quote'),
      pdf('survey.pdf', 'Building survey'),
      pdf('warranty.pdf', 'Washing machine warranty'),
      photo('garden.jpg'),
      photo('damp-patch.jpg'),
      photo('new-kitchen.jpg'),
      xlsx('renovation-costs.xlsx'),
      text('to-do.txt', [
        'Jobs, as of {date}',
        '- paint the back bedroom',
        '- gutter over the porch ({first})',
      ]),
      text('tradespeople.md', [
        '# Tradespeople',
        '',
        'Plumber came {date}. {first} has his number.',
      ]),
    ],
    school: [
      pdf('term-dates.pdf', 'Term dates'),
      pdf('school-report.pdf', 'School report'),
      pdf('trip-letter.pdf', 'School trip letter'),
      pdf('uniform-list.pdf', 'Uniform list'),
      docx('science-project.docx'),
      docx('history-essay.docx'),
      xlsx('spelling-scores.xlsx'),
      text('reading-log.txt', ['Reading log from {date}', 'Chapter {number} tonight', 'Signed: {first}']),
      text('homework.md', ['# Homework', '', 'Maths sheet due {date}. {first} helps on Tuesdays.']),
      text('clubs.txt', ['After school clubs from {date}', 'Monday: football', 'Thursday: chess']),
    ],
    photos: [
      photo('beach.jpg'),
      photo('birthday.jpg'),
      photo('dog.jpg'),
      photo('wedding.jpg'),
      photo('first-day-at-school.jpg'),
      photo('christmas.jpg'),
      photo('camping.jpg'),
      photo('grandparents.jpg'),
      photo('snow.jpg'),
      photo('garden-party.jpg'),
    ],
    recipes: [
      pdf('banana-bread.pdf', 'Banana bread'),
      pdf('sourdough.pdf', 'Sourdough starter'),
      xlsx('meal-plan.xlsx'),
      docx('family-recipes.docx'),
      photo('birthday-cake.jpg'),
      text('lasagne.txt', ['Lasagne, the way {first} makes it', 'Brown the mince first.', 'Written down {date}']),
      text('curry.md', ['# Friday curry', '', 'Serves {number}. From {first}, {date}.']),
      text('shopping-list.txt', ['Shopping, {date}', 'onions', 'rice', 'coriander']),
      text('pancakes.txt', ['Pancakes for {number}', 'Flour, eggs, milk. {first} does the flipping.', '{date}']),
      text('soup.md', ['# Soup', '', 'Leek and potato. Noted {date}.']),
    ],
  },
  university: {
    research: [
      pdf('draft-paper.pdf', 'Draft paper'),
      pdf('literature-review.pdf', 'Literature review'),
      pdf('ethics-approval.pdf', 'Ethics approval'),
      pdf('poster.pdf', 'Conference poster'),
      xlsx('raw-data.xlsx'),
      xlsx('equipment-bookings.xlsx'),
      docx('methods.docx'),
      text('results.csv', ['run,date,samples,operator', '1,{date},{number},{person}', '2,{date},{number},{person}']),
      text('lab-notes.md', ['# Lab notes', '', 'Repeat the second run. {first}, {date}.']),
      text('reading.txt', ['To read before the group meeting on {date}', '- the review {person} sent round']),
    ],
    theses: [
      pdf('thesis-draft.pdf', 'Thesis draft'),
      pdf('thesis-final.pdf', 'Thesis'),
      pdf('viva-report.pdf', 'Viva report'),
      pdf('abstract.pdf', 'Abstract'),
      docx('chapter-three.docx'),
      docx('corrections.docx'),
      xlsx('submission-dates.xlsx'),
      text('feedback.txt', ['Feedback from {person}, {date}', 'Tighten the method section.']),
      text('supervision.md', ['# Supervision', '', 'Met {person} on {date}. Next: chapter four.']),
      text('bibliography.txt', ['Sources added {date}', '{number} new references']),
    ],
    lectures: [
      pdf('week-one.pdf', 'Week one'),
      pdf('week-two.pdf', 'Week two'),
      pdf('week-three.pdf', 'Week three'),
      pdf('exam-paper.pdf', 'Past exam paper'),
      pdf('module-handbook.pdf', 'Module handbook'),
      docx('reading-list.docx'),
      docx('seminar-questions.docx'),
      xlsx('attendance.xlsx'),
      xlsx('marks.xlsx'),
      text('office-hours.txt', ['Office hours from {date}', 'Tuesdays with {person}']),
    ],
    admin: [
      xlsx('room-bookings.xlsx'),
      xlsx('budget-codes.xlsx'),
      pdf('exam-timetable.pdf', 'Exam timetable'),
      pdf('fire-wardens.pdf', 'Fire wardens'),
      pdf('committee-minutes.pdf', 'Committee minutes'),
      docx('travel-claim.docx'),
      docx('annual-review.docx'),
      text('staff-list.txt', ['Department staff, {date}', '{person}', '{person}', '{person}']),
      text('open-day.md', ['# Open day', '', '{number} visitors booked. {first} runs the tours. Set for {date}.']),
      text('post-room.txt', ['Parcels waiting since {date}', 'for {person}']),
    ],
    grants: [
      pdf('proposal.pdf', 'Grant proposal'),
      pdf('award-letter.pdf', 'Award letter'),
      pdf('final-report.pdf', 'Final report'),
      pdf('call-for-proposals.pdf', 'Call for proposals'),
      xlsx('budget.xlsx'),
      xlsx('spend-to-date.xlsx'),
      docx('report.docx'),
      docx('impact-statement.docx'),
      text('deadlines.txt', ['Next deadline {date}', 'Lead: {person}']),
      text('costings.csv', ['item,amount', 'equipment,{amount}', 'travel,{amount}', 'staff,{amount}']),
    ],
  },
  public: {
    minutes: [
      pdf('minutes-march.pdf', 'Meeting minutes'),
      pdf('minutes-june.pdf', 'Meeting minutes'),
      pdf('agm-minutes.pdf', 'Annual general meeting minutes'),
      pdf('standing-orders.pdf', 'Standing orders'),
      docx('minutes-april.docx'),
      docx('minutes-may.docx'),
      xlsx('attendance.xlsx'),
      text('agenda.txt', ['Agenda for {date}', 'Apologies, minutes, any other business', 'Chair: {person}']),
      text('actions.md', ['# Actions', '', '{person} to chase the council by {date}.']),
      text('apologies.txt', ['Apologies for {date}', '{person}', '{person}']),
    ],
    planning: [
      pdf('site-plan.pdf', 'Site plan'),
      pdf('planning-application.pdf', 'Planning application'),
      pdf('access-statement.pdf', 'Access statement'),
      pdf('tree-survey.pdf', 'Tree survey'),
      docx('consultation.docx'),
      docx('objection-response.docx'),
      photo('site-visit.jpg'),
      photo('car-park.jpg'),
      xlsx('responses.xlsx'),
      text('timeline.md', ['# Timeline', '', 'Submitted {date}. Decision due in {number} weeks.']),
    ],
    notices: [
      pdf('opening-hours.pdf', 'Opening hours'),
      pdf('events-poster.pdf', 'Events poster'),
      pdf('lost-property.pdf', 'Lost property'),
      pdf('volunteers-wanted.pdf', 'Volunteers wanted'),
      docx('closure-notice.docx'),
      docx('newsletter.docx'),
      text('events.txt', ['What is on at {place} from {date}', 'Craft morning on Saturday', 'Ask {first} at the desk']),
      text('noticeboard.md', ['# Noticeboard', '', 'Pinned {date}: the lift is out until further notice.']),
      text('holiday-hours.txt', ['Holiday hours from {date}', 'Closed on bank holidays']),
      text('rooms.csv', ['date,room,booked_by', '{date},hall,{person}', '{date},meeting room,{person}']),
    ],
    budgets: [
      xlsx('annual-budget.xlsx'),
      xlsx('grant-tracker.xlsx'),
      xlsx('petty-cash.xlsx'),
      pdf('budget-summary.pdf', 'Budget summary'),
      pdf('funding-bid.pdf', 'Funding bid'),
      pdf('audit.pdf', 'Independent examination'),
      docx('treasurer-report.docx'),
      text('grants.csv', ['date,grant,amount,status', '{date},community fund,{amount},awarded']),
      text('spending.txt', ['Spent since {date}: {amount}', 'Signed off by {person}']),
      text('fees.md', ['# Room hire fees', '', 'Hall: {amount} a session. Reviewed {date}.']),
    ],
    maintenance: [
      xlsx('repairs.xlsx'),
      xlsx('contractors.xlsx'),
      pdf('roof-survey.pdf', 'Roof survey'),
      pdf('electrical-test.pdf', 'Electrical installation report'),
      pdf('legionella.pdf', 'Water safety assessment'),
      docx('maintenance-plan.docx'),
      photo('boiler.jpg'),
      photo('broken-window.jpg'),
      text('faults.txt', ['Reported {date}', '- lights flicker in the hall', 'Logged by {first}']),
      text('keyholders.md', ['# Keyholders', '', '{person}', '{person}', 'Checked {date}.']),
    ],
  },
  hacker: {
    talks: [
      pdf('lightning-talk.pdf', 'Lightning talk'),
      pdf('intro-to-sdr.pdf', 'Intro to software defined radio'),
      pdf('lockpicking-basics.pdf', 'Lockpicking basics'),
      pdf('retro-computing.pdf', 'Retro computing'),
      photo('stage.jpg'),
      photo('audience.jpg'),
      docx('call-for-talks.docx'),
      text('schedule.md', ['# Talks', '', 'Slots are ten minutes. First up {date}: {person}.']),
      text('speakers.csv', ['date,speaker,topic', '{date},{person},mesh networks', '{date},{person},keyboards']),
      text('feedback.txt', ['Feedback from the night of {date}', 'More soldering, less slides.']),
    ],
    zines: [
      pdf('issue-one.pdf', 'Issue one'),
      pdf('issue-two.pdf', 'Issue two'),
      pdf('issue-three.pdf', 'Issue three'),
      pdf('special-issue.pdf', 'Special issue'),
      docx('editorial.docx'),
      docx('layout-notes.docx'),
      photo('cover-art.jpg'),
      text('submissions.txt', ['Submissions open until {date}', 'Plain text, under a page. Send to {first}.']),
      text('contributors.md', ['# Contributors', '', '{person}', '{person}', '{person}']),
      text('print-run.txt', ['Print run on {date}: {number} copies']),
    ],
    writeups: [
      pdf('soldering-guide.pdf', 'Soldering guide'),
      pdf('reflow-oven.pdf', 'Building a reflow oven'),
      pdf('keyboard-build.pdf', 'Keyboard build'),
      photo('oscilloscope.jpg'),
      docx('project-log.docx'),
      text('badge-teardown.md', ['# Badge teardown', '', 'Four screws. {first} got it open on {date}.']),
      text('ctf-notes.txt', ['CTF on {date}', 'We came third. Team: {first}, {first}, {first}']),
      text('radio-log.txt', ['Listening log from {date}', 'Weather satellite pass at dawn']),
      text('parts.csv', ['date,part,qty', '{date},resistors,{number}', '{date},headers,{number}']),
      text('mesh-notes.md', ['# Mesh', '', '{number} nodes up on the roof. Checked {date}.']),
    ],
    meetups: [
      pdf('code-of-conduct.pdf', 'Code of conduct'),
      pdf('floor-plan.pdf', 'Floor plan'),
      xlsx('pizza-order.xlsx'),
      xlsx('membership.xlsx'),
      docx('meetup-announcement.docx'),
      text('attendance.csv', ['date,people', '{date},{number}', '{date},{number}']),
      text('door-rota.txt', ['Door duty from {date}', '{person}', '{person}']),
      text('venue.md', ['# Venue', '', 'Doors at seven. {first} has the keys to {place}.']),
      text('dues.txt', ['Dues collected on {date}: {amount}', 'Held by {person}']),
      text('ideas.txt', ['Ideas for next month, {date}', 'Repair cafe night', 'Badge workshop']),
    ],
    photos: [
      photo('workbench.jpg'),
      photo('meetup.jpg'),
      photo('badge.jpg'),
      photo('soldering-night.jpg'),
      photo('rooftop-antenna.jpg'),
      photo('retro-corner.jpg'),
      photo('3d-printer.jpg'),
      photo('group-shot.jpg'),
      photo('laser-cutter.jpg'),
      photo('cable-drawer.jpg'),
    ],
  },
  iot: {
    datasheets: [
      pdf('controller-datasheet.pdf', 'Controller datasheet'),
      pdf('sensor-datasheet.pdf', 'Sensor datasheet'),
      pdf('power-supply.pdf', 'Power supply datasheet'),
      pdf('relay-module.pdf', 'Relay module datasheet'),
      pdf('antenna.pdf', 'Antenna datasheet'),
      xlsx('parts-list.xlsx'),
      docx('wiring-notes.docx'),
      text('pinout.txt', ['Pinout, checked {date}', 'Ground is the square pad.']),
      text('bill-of-materials.csv', ['part,qty', 'board,{number}', 'enclosure,{number}']),
      text('README.md', ['# Datasheets', '', 'Kept for the unit at {place}. Collected by {first}.']),
    ],
    qa: [
      xlsx('defects.xlsx'),
      xlsx('burn-in.xlsx'),
      pdf('test-plan.pdf', 'Test plan'),
      pdf('field-report.pdf', 'Field report'),
      docx('fault-writeup.docx'),
      photo('board.jpg'),
      photo('scorch-mark.jpg'),
      text('test-log.csv', ['date,unit,result,tester', '{date},{number},pass,{person}', '{date},{number},fail,{person}']),
      text('known-issues.md', ['# Known issues', '', 'Drops off the network after a power cut. Seen {date}.']),
      text('retest.txt', ['Retest booked for {date}', 'Owner: {first}']),
    ],
    certification: [
      pdf('declaration-of-conformity.pdf', 'Declaration of conformity'),
      pdf('test-report.pdf', 'Radio test report'),
      pdf('safety-report.pdf', 'Electrical safety report'),
      pdf('emc-report.pdf', 'Electromagnetic compatibility report'),
      photo('label.jpg'),
      photo('rating-plate.jpg'),
      docx('technical-file.docx'),
      xlsx('certificates.xlsx'),
      text('renewals.txt', ['Certificates to renew by {date}', 'Chased by {person}']),
      text('lab-contact.md', ['# Test lab', '', 'Booked {date}. Contact through {first}.']),
    ],
    manuals: [
      pdf('user-manual.pdf', 'User manual'),
      pdf('quick-start.pdf', 'Quick start guide'),
      pdf('installation-guide.pdf', 'Installation guide'),
      pdf('troubleshooting.pdf', 'Troubleshooting'),
      pdf('warranty.pdf', 'Warranty'),
      docx('install-notes.docx'),
      photo('install-photo.jpg'),
      text('reset.txt', ['How {first} reset it on {date}', 'Hold the button for ten seconds.']),
      text('service-history.csv', ['date,work,engineer', '{date},annual service,{person}']),
      text('manual-notes.md', ['# Notes', '', 'The unit at {place} was fitted on {date}.']),
    ],
  },
};

/** The cameras a photo was taken with where the network has no phone to have taken it.
 *  Each name stands alone in a `strings` listing, so every one is at least four
 *  characters, and none carries a decimal. */
export const CAMERAS: readonly { readonly make: string; readonly model: string }[] = [
  { make: 'Canon', model: 'Canon EOS R6' },
  { make: 'Canon', model: 'Canon EOS M50' },
  { make: 'NIKON CORPORATION', model: 'NIKON Z 6' },
  { make: 'NIKON CORPORATION', model: 'NIKON D7500' },
  { make: 'FUJIFILM', model: 'X-T4' },
  { make: 'SONY', model: 'ILCE-7M3' },
  { make: 'OLYMPUS CORPORATION', model: 'E-M10MarkIII' },
];

/** The models a phone on the network may be, by the kind its name says it is. A phone is
 *  one model for its whole life, so every photo it took carries the same one. */
export const PHONE_MODELS: Readonly<
  Record<string, readonly { readonly make: string; readonly model: string }[]>
> = {
  iphone: [
    { make: 'Apple', model: 'iPhone 12' },
    { make: 'Apple', model: 'iPhone 13' },
    { make: 'Apple', model: 'iPhone 13 mini' },
    { make: 'Apple', model: 'iPhone 14 Pro' },
    { make: 'Apple', model: 'iPhone 15' },
    { make: 'Apple', model: 'iPhone SE' },
  ],
  android: [
    { make: 'Google', model: 'Pixel 7' },
    { make: 'Google', model: 'Pixel 8 Pro' },
    { make: 'Google', model: 'Pixel 6a' },
    { make: 'Samsung', model: 'Galaxy S23' },
    { make: 'Samsung', model: 'Galaxy A54' },
    { make: 'Samsung', model: 'Galaxy S22 Ultra' },
  ],
};
