/**
 * Build-time secret encoder. Reads the committed plaintext `secrets` map and
 * emits the gitignored `src/core/secrets/__encoded.ts`, where each value is
 * XOR+Base64 obfuscated (see `contentCodec.ts`). Run automatically by the
 * `predev`/`prebuild`/`pretest*` npm hooks so the generated file is always
 * fresh. Obfuscation, not secrecy — it only keeps spoilers out of a grep of
 * the deployed bundle.
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { encodeContent } from '../src/core/secrets/contentCodec';
import { secrets } from '../src/core/secrets/secrets';

const scriptDir = dirname(fileURLToPath(import.meta.url));

const encodedEntries = Object.entries(secrets).map(
  ([key, value]) => [key, encodeContent(value)] as const,
);

const lines = [
  '// Auto-generated by scripts/encode.ts — do not edit.',
  "import { decodeContent } from './contentCodec';",
  '',
  'const d = (encoded: string): string => decodeContent(encoded);',
  '',
  'export const secrets = {',
  ...encodedEntries.map(([key, encoded]) => `  ${key}: d(${JSON.stringify(encoded)}),`),
  '} as const;',
  '',
];

const outPath = resolve(scriptDir, '../src/core/secrets/__encoded.ts');
writeFileSync(outPath, lines.join('\n'), 'utf-8');
console.log(`Wrote ${outPath}`);
