import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { encodeContent } from '../src/utils/contentCodec';
import { secrets } from '../src/secrets/secrets';

const __dirname = dirname(fileURLToPath(import.meta.url));

const encodedSecrets = Object.entries(secrets).map(
  ([key, value]) => [key, encodeContent(value)] as const,
);

const secretsLines = [
  '// Auto-generated by scripts/encode.ts — do not edit',
  "import { decodeContent } from '../utils/contentCodec';",
  '',
  'const d = (encoded: string): string => decodeContent(encoded);',
  '',
  'export const secrets = {',
  ...encodedSecrets.map(([key, encoded]) => `  ${key}: d(${JSON.stringify(encoded)}),`),
  '} as const;',
  '',
];

const secretsOutPath = resolve(__dirname, '../src/secrets/__encoded.ts');
writeFileSync(secretsOutPath, secretsLines.join('\n'), 'utf-8');
console.log(`Wrote ${secretsOutPath}`);
