import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { localhost } from '../src/filesystem/machines/localhost';
import { fileserver } from '../src/filesystem/machines/fileserver';
import { encodeContent, encodeFileSystem } from '../src/utils/contentCodec';
import { secrets } from '../src/secrets/secrets';

const __dirname = dirname(fileURLToPath(import.meta.url));

const machines = [
  ['localhost', localhost],
  ['fileserver', fileserver],
] as const;

const encodedEntries = machines.map(
  ([name, tree]) => [name, JSON.stringify(encodeFileSystem(tree))] as const,
);

const fsLines = [
  '// Auto-generated by scripts/encode.ts — do not edit',
  "import type { FileNode } from '../types';",
  "import { decodeFileSystem } from '../../utils/contentCodec';",
  '',
  'const p = (json: string): FileNode => decodeFileSystem(JSON.parse(json));',
  '',
  ...encodedEntries.map(
    ([name, json]) => `export const ${name}: FileNode = p(${JSON.stringify(json)});`,
  ),
  '',
];

const fsOutPath = resolve(__dirname, '../src/filesystem/machines/__encoded.ts');
writeFileSync(fsOutPath, fsLines.join('\n'), 'utf-8');
console.log(`Wrote ${fsOutPath}`);

const encodedSecrets = Object.entries(secrets).map(
  ([key, value]) => [key, encodeContent(value)] as const,
);

const secretsLines = [
  '// Auto-generated by scripts/encode.ts — do not edit',
  "import { decodeContent } from '../utils/contentCodec';",
  '',
  'const d = (encoded: string): string => decodeContent(encoded);',
  '',
  'export const secrets = {',
  ...encodedSecrets.map(([key, encoded]) => `  ${key}: d(${JSON.stringify(encoded)}),`),
  '} as const;',
  '',
];

const secretsOutPath = resolve(__dirname, '../src/secrets/__encoded.ts');
writeFileSync(secretsOutPath, secretsLines.join('\n'), 'utf-8');
console.log(`Wrote ${secretsOutPath}`);
