/**
 * What a generated IoT box keeps because of the device it is: a printer its print
 * server's config and spool, a camera its events. It sits on top of the small Linux
 * board every IoT box already is, and moves nothing about that board.
 *
 * Which device a box is comes off its name, as its role does, so a box named `printer-44`
 * on a scan is a printer on disk.
 *
 * Every draw comes from the box's own `device-` stream, so giving a box a device moves
 * no account, password, page or history already generated.
 */

import { createPrng, type Prng } from './prng';
import { dir, file, ROOT_FILE, TRAVERSABLE_DIR } from './baseFs';
import { uuid } from './etcContent';
import { CUPSD_CONFS, PRINTER_MODELS } from './pools/devices';
import type { Directory, FileNode } from '../filesystem/types';
import type { LanHost } from './generateHomeLan';

export type DeviceKind = 'camera' | 'recorder' | 'printer' | 'climate' | 'media' | 'plug' | 'lock';

/** Prefixes share a kind only where they are one device in another flavour: a doorbell
 *  and a baby monitor are cameras, a thermostat is a sensor that also sets the heat. */
const KIND_BY_PREFIX: ReadonlyMap<string, DeviceKind> = new Map([
  ['cam', 'camera'],
  ['doorbell', 'camera'],
  ['babycam', 'camera'],
  ['nvr', 'recorder'],
  ['printer', 'printer'],
  ['sensor', 'climate'],
  ['thermostat', 'climate'],
  ['tv', 'media'],
  ['speaker', 'media'],
  ['plug', 'plug'],
  ['lock', 'lock'],
]);

/** The device a box calling itself `hostname` is, or undefined for any other box. */
export const deviceKindOf = (hostname: string): DeviceKind | undefined => {
  const separator = hostname.lastIndexOf('-');
  if (separator < 0) return undefined;
  return KIND_BY_PREFIX.get(hostname.slice(0, separator));
};

/** What a device adds to its box: entries for `/etc`, and the configs among them that
 *  root's history may name. */
export type DeviceFiles = {
  readonly etc: Readonly<Record<string, FileNode>>;
  readonly configPaths: readonly string[];
};

const ALPHANUMERIC = 'ABCDEFGHJKLMNPQRSTUVWXYZ0123456789';

const serialNumber = (prng: Prng): string =>
  Array.from({ length: 12 }, () => ALPHANUMERIC[prng.nextInt(0, ALPHANUMERIC.length - 1)]).join('');

/** The one queue the print server keeps, written as cupsd writes it back. The printer
 *  hangs off the board's USB port, so its device URI names no host and no port. */
const printersConf = (prng: Prng, model: string, queue: string): string => {
  const [make = model, ...rest] = model.split(' ');
  const product = encodeURIComponent(rest.join(' '));
  return [
    '# Printer configuration file for CUPS',
    '# Written by cupsd',
    '# DO NOT EDIT THIS FILE WHEN CUPSD IS RUNNING',
    'NextPrinterId 2',
    `<DefaultPrinter ${queue}>`,
    'PrinterId 1',
    `UUID urn:uuid:${uuid(prng)}`,
    `Info ${model}`,
    `MakeModel ${model}`,
    `DeviceURI usb://${make}/${product}?serial=${serialNumber(prng)}`,
    'State Idle',
    'Type 8425492',
    'Accepting Yes',
    'Shared Yes',
    'JobSheets none none',
    'QuotaPeriod 0',
    'PageLimit 0',
    'KLimit 0',
    'OpPolicy default',
    'ErrorPolicy retry-job',
    '</DefaultPrinter>',
    '',
  ].join('\n');
};

const printerFiles = (prng: Prng): DeviceFiles => {
  const model = prng.pick(PRINTER_MODELS);
  const queue = model.replaceAll(' ', '_');
  const cupsd = prng.pick(CUPSD_CONFS);
  const cups: Directory = dir(
    {
      'cupsd.conf': file(cupsd, ROOT_FILE),
      'printers.conf': file(printersConf(prng, model, queue), ROOT_FILE),
    },
    TRAVERSABLE_DIR,
  );
  return {
    etc: { cups },
    configPaths: ['/etc/cups/cupsd.conf', '/etc/cups/printers.conf'],
  };
};

/** What the device `host` is keeps on disk, or null where its kind keeps nothing of its
 *  own yet and the box keeps the generic device config instead. */
export const buildDevice = (essid: string, host: LanHost): DeviceFiles | null => {
  const kind = deviceKindOf(host.hostname);
  if (kind !== 'printer') return null;
  return printerFiles(createPrng(`device-${essid}-${host.ip}`));
};
