export const secrets = {
  WIFI_PASSWORD: 'cr4ck3d_w1f1',
  MISSION_PASSWORDS: JSON.stringify([
    's3cur3!',
    'p4ssw0rd',
    'l3tm3in',
    'ch4ng3m3',
    'adm1n123',
    'r00tpass',
    'b4ckd00r',
    'h4ck3r',
    'n3tw0rk',
    'syst3m!',
    'tr4nsf3r',
    'd4t4b4s3',
    'w3bs3rv3r',
    'f1l3s3rv',
    'w0rkst4t',
    'qu3ry!',
    'd3ploy',
    'st4ging',
    'pr0duct1on',
    'd3v3l0p',
  ]),
  GUEST_PASSWORDS: JSON.stringify([
    'guest',
    'guest123',
    'password',
    'letmein',
    'welcome',
    'changeme',
  ]),
} as const;
